3-add S block
EPAM-Online-Courses/tetris pull request #20
Opened 2021-01-05 22:16 UTC by oskar117

2021-01-06 18:36 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/block/SBlock.java
> + * The class is derived from {@link Block} and represents S-shaped block:
There's no need to write what this class extends - it's added automatically by the `javadoc` tool.

2021-01-06 18:36 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        boolean containsSBlock = blockFeed.blocks().stream().map(Supplier::get).anyMatch(e -> e instanceof SBlock);
It would be nice to preserve the layout of the method chain as in the test above. That helps greatly when debugging the code (IDEA shows it quite nicely), You can also comment out a single line in the middle of the chain much more easily.

2021-01-06 18:36 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        boolean containsSBlock = blockFeed.blocks().stream().map(Supplier::get).anyMatch(e -> e instanceof SBlock);
In addition, there was a GWT convention applied in by .your predecessor. As the English proverb says, "When in Rome, do as Romans do".

2021-01-06 18:36 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        boolean containsSBlock = blockFeed.blocks().stream().map(Supplier::get).anyMatch(e -> e instanceof SBlock);
Also, this test asserts a weaker condition than the one above. It only checks the existence of the "S" block, Multiple "S" blocks could affect the random distribution of the blocks - they would be statistically "more frequent". This might make sense in the future as a part of difficulty level raising, but since the previous one was already accepted, it became a requirement, so a similar requirement should be applied here to preserve the balance.

2021-01-06 18:55 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/SBlockTests.java
> +public class SBlockTests {
There's already a file with a `*Test` suffix (which is good and common), it's good to follow some naming convention.

2021-01-06 23:30 UTC, TJB4epam commented
I've just merged other changes. Make sure you have all you need and that this works after you merge the new master.

PS. When opening a pull-request - DO add a description. Be decent if you hope for a decent review.

2021-01-07 08:50 UTC, oskar117 commented
I have implemented changes according to your review @pkierat-epam
I apologise for lack of description

2021-01-07 10:36 UTC, TJB4epam requested changes

2021-01-07 10:36 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/block/BlockFeed.java
> +        OBlock::new, SBlock::new, LBlock::new
Why before the LBlock? Not that I particularly mind, but usually the new items should land at the end?

2021-01-07 10:36 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/block/SBlock.java
> + * <pre> ##<br/>## </pre>
Nice touch. :+1:

2021-01-07 10:36 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/block/SBlock.java
> +}
I thank you for the tests.

Would you agree that they duplicate the `LBlock` tests? If so - what about CHANGING them in such a way that we have same body of tests (where applicable) and just different data is being fed to those uniform tests?

In the spirit of DRY - Don't Repeat Yourself.

2021-01-07 10:36 UTC, TJB4epam commented on src/test/resources/testng.xml
> +            <class name="com.epam.prejap.tetris.block.SBlockTest"/>
Mighty fine but we want groups as well, to be able to run groups / scenarios:

1. check if all is fine with ALL blocks
2. check if all is fine with JUST an S-block
3. just an I-block
4. ...

So please update the grouping of the tests appropriately, as well as the POM.

While we're on the POM side - please update the version - that change brings us up one minor version number.

2021-01-07 19:07 UTC, TJB4epam requested changes
1. POM version still not bumped up.
2. Groups as you define them are an improvement but you're actually defining TESTS rather than GROUPS. Also, I don't have groups for just an IBlock or just an SBlock.

2021-01-08 19:11 UTC, oskar117 commented
I've applied more suggestions @pkierat-epam or @TJB4epam

2021-01-09 07:41 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        boolean containsSBlock = blockFeed.blocks().stream().map(Supplier::get).anyMatch(e -> e instanceof SBlock);
@oskar117 care to reply?

2021-01-09 07:41 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/SBlockTests.java
> +public class SBlockTests {
Alek for some reason didn't reply but this is fixed.

2021-01-09 07:43 UTC, TJB4epam commented on src/test/resources/testng.xml
> +            <class name="com.epam.prejap.tetris.block.SBlockTest"/>
I see you have made some changes. Would like to hear if this is now done or not? Generally - remarks should have replies. :-)

2021-01-09 08:40 UTC, oskar117 commented on src/main/java/com/epam/prejap/tetris/block/SBlock.java
> +}
There are code dublicates already in the repo, so I think that this should be a new issue for that.

2021-01-09 08:42 UTC, oskar117 commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        boolean containsSBlock = blockFeed.blocks().stream().map(Supplier::get).anyMatch(e -> e instanceof SBlock);
Everything done

2021-01-09 08:48 UTC, oskar117 commented on src/test/resources/testng.xml
> +            <class name="com.epam.prejap.tetris.block.SBlockTest"/>
I wish to :). Also, should my replies look like "done" if I don't have any questions/comments?

2021-01-11 20:40 UTC, pkierat-epam commented on src/test/resources/testng.xml
> +            <class name="com.epam.prejap.tetris.block.SBlockTest"/>
"Done" is fine, or you can use emoji reactions if you like. Any form of response is better than silence.

2021-01-12 19:23 UTC, pkierat-epam requested changes
This is the last change that stops me from merging.

2021-01-12 19:23 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +@Test(groups = "IBlock")
What is the reason for such change in the group name? This way, we lose the ability to run all the block tests at once. For me, it would be better to leave the original, more general group and just add a specific one. ('groups' is plural after all.)

2021-01-12 20:12 UTC, oskar117 commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +@Test(groups = "IBlock")
But there are metagroups defined in testng.xml, so you can run just block group anyway.

2021-01-12 20:20 UTC, oskar117 commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +@Test(groups = "IBlock")
Oh, I see that it works anyway. Fixed now.

2021-01-12 20:53 UTC, pkierat-epam commented
I was just going to merge your PR... when I spotted that after running the app:
```
Time: 00:00:01
+--------------------+
|                    |
|                    |
|          ##        |
|         ##         |
|                    |
|                    |
|                    |
|                    |
|                    |
|                    |
+--------------------+
```
Yes, the O block is slanted... On master, I wasn't able to replicate it. What's really interesting is that all the tests pass :open_mouth:

2021-01-12 21:12 UTC, oskar117 commented
> I was just going to merge your PR... when I spotted that after running the app:
> 
> ```
> Time: 00:00:01
> +--------------------+
> |                    |
> |                    |
> |          ##        |
> |         ##         |
> |                    |
> |                    |
> |                    |
> |                    |
> |                    |
> |                    |
> +--------------------+
> ```
> 
> Yes, the O block is slanted... On master, I wasn't able to replicate it. What's really interesting is that all the tests pass 😮

Are you sure that it is not just my SBlock? I've run game milion times by now and everything works fine. (Perhaps I can't see something)

2021-01-13 07:31 UTC, TJB4epam commented
> >  the O block is slanted... On master, I wasn't able to replicate it. What's really interesting is that all the tests pass open_mouth
> 
> Are you sure that it is not just my SBlock? I've run game milion times by now and everything works fine. (Perhaps I can't see something)

@pkierat-epam  This is just taken from a fetched sources from Aleksander. I lean to @oskar117  explanation. Breaks added by me for readability:

```
Time: 00:00:10
+--------------------+
|         #          |
|        ##          |
|        ###         |

|         ##         |
|        ##          |

|        ##          |
|        ##          |

|         #          |
|         #          |
|         ##         |
+--------------------+
```

We have L, then O, then S - S is the slanted O.

2021-01-13 07:32 UTC, TJB4epam approved these changes
Good for merging - @pkierat-epam take a look at my comment w.r.t. the slanted-o block.

2021-01-13 11:03 UTC, merged