5 add i block
EPAM-Online-Courses/tetris pull request #22
Opened 2021-01-06 05:48 UTC by LukaszProkop

2021-01-06 23:32 UTC, TJB4epam commented
I've just merged other changes. Make sure you have all you need and that this works after you merge the new master. GitHub for one reports that there are conflicts in the testng.xml file.

2021-01-07 01:11 UTC, LukaszProkop commented
@TJB4epam  Done

2021-01-07 10:40 UTC, TJB4epam requested changes

2021-01-07 10:40 UTC, TJB4epam commented on src/test/resources/testng.xml
> +                <include name="IBlock"/>
What should be the difference between "Block" and "IBlock" groups? When would I want to run one, but not another? When will I want to run both?

I have a feeling that all tests in the IBlock group should belong to a Block group. Furthermore I'd want an LGroup just for the L-Block. What say you?

2021-01-07 10:40 UTC, TJB4epam commented on src/test/resources/testng.xml
> +                <include name="IBlock"/>
Also - you owe us two minor version numbers Łukasz. One for this, one for LBlock, so I'd like that to be bumped up in the POM (it's no longer Tetris 0.1).

2021-01-07 10:40 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +import java.lang.reflect.Field;
Nifty. Will have to look at it deeper later, cause now I'm rushing to a meeting. Please, focus on other changes I requested in the meantime.

2021-01-07 19:09 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +        Field[] fields = IBlock.class.getDeclaredFields();
Well, it's nice to see Reflection API used, but... there's a package method for that already. :D So, nope. :-) Paweł :+1:

2021-01-07 19:10 UTC, TJB4epam commented
Closing - reflection was a nice but in the end a redundant touch. Please correct what was required and do reopen. Thank you!

2021-01-08 17:45 UTC, LukaszProkop commented
@pkierat-epam @TJB4epam All necessary corrections have been implemented and all the files are up to date.

2021-01-08 18:06 UTC, merged

2021-01-08 18:07 UTC, pkierat-epam commented
Points: 19