2-add J shaped block
EPAM-Online-Courses/tetris pull request #23
Opened 2021-01-06 14:42 UTC by LucasBulczak

This Pull Request introduce new block to Tetris Game - J-shaped block as mentioned on issue #2.

@pkierat-epam, I would appreciate your feedback ;-)

2021-01-06 19:23 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/block/JBlock.java
> +     * Constructor that delegates the creation of the object to the constructor of the superclass.
Are you sure you want to make the delegation to the super-constructor a part of the contract here? For me it's rather an implementation detail.

2021-01-06 19:23 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/JBlockTest.java
> +}
New line character missing at EOF.

2021-01-06 19:23 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/block/BlockFeed.java
> +        OBlock::new, LBlock::new, JBlock::new
This change is not tested in any way. See the tests introduced by your predecessor.

2021-01-06 19:26 UTC, LucasBulczak commented on src/main/java/com/epam/prejap/tetris/block/JBlock.java
> +     * Constructor that delegates the creation of the object to the constructor of the superclass.
Sorry, I was testing the button and thought I can always undo :-)

2021-01-06 22:42 UTC, LucasBulczak commented
@pkierat-epam  I have made some changes. I would be really grateful if you could take another look :-)

2021-01-06 23:32 UTC, TJB4epam commented
I've just merged other changes. Make sure you have all you need and that this works after you merge the new master. GitHub for one reports conflicts in the testng.xml file.

2021-01-07 08:14 UTC, LucasBulczak commented
@TJB4epam, thanks for the information. Conflicts resolved! 

Can you take a look at the BlockFeedTestFactory test class? I wanted to eliminate code duplication in the current ones so that we could only add a new figure class to it and all tests would be performed without further typing :-)

2021-01-07 08:14 UTC, LucasBulczak commented on src/test/java/com/epam/prejap/tetris/block/JBlockTest.java
> +}
Done.

2021-01-07 08:15 UTC, LucasBulczak commented on src/main/java/com/epam/prejap/tetris/block/BlockFeed.java
> +        OBlock::new, LBlock::new, JBlock::new
I believe the job is done :-)

2021-01-07 11:11 UTC, TJB4epam requested changes

2021-01-07 11:11 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/block/JBlock.java
> + * <p><br>
Why do we open a paragraph here or introduce a line break?

2021-01-07 11:11 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +                .anyMatch(this::isInstanceOf);
Nice. :+1:

2021-01-07 11:11 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +                .count();
An improvement indeed. :+1:

2021-01-07 11:11 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +}
:+1:

2021-01-07 11:11 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        return e.getClass().getSimpleName().equals(blockClassName);
What would you say we gain by this change? Aside from the ability of calling a method ref instead of "instanceof" operator.

2021-01-07 11:11 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/JBlockTest.java
> +        softAssert.assertTrue(actualRows == expectedImage.length);
You are asserting equality, so please make it via `assertEquals`, not via `assertTrue(a == b)`.

Also, I'd like the messages on both conditions, that way the final report by soft assertion would be complete.

2021-01-07 11:11 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTestFactory.java
> +public class BlockFeedTestFactory {
Nifty trick. Please write a word of comment for others, who may not necessarily think like you.

This definitely streamlines the testing, so it's a piece of test infrastructure, hence a word of comment how to use it for others is required.

2021-01-07 11:28 UTC, LucasBulczak commented on src/main/java/com/epam/prejap/tetris/block/JBlock.java
> + * <p><br>
It was part of a broader description. Thanks for reminding me.

2021-01-07 11:37 UTC, LucasBulczak commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        return e.getClass().getSimpleName().equals(blockClassName);
In my humble opinion, we gain two things:
1. All operations on the stream are at the same level of abstraction -> are more readable.
2. We can use BlockFeedTestFactory and not duplicate code for other blocks.

Do you see any error in my reasoning? :-)

2021-01-07 11:39 UTC, LucasBulczak commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTestFactory.java
> +public class BlockFeedTestFactory {
Thank you ;-)

Would such a code be acceptable in production, or would comparing classes based on their names somehow disqualify in some situations?

2021-01-07 11:54 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTestFactory.java
> +public class BlockFeedTestFactory {
Why not compare the classes directly?

2021-01-07 11:54 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        return e.getClass().getSimpleName().equals(blockClassName);
Apart from the `instanceof` operator, there's also a method in the Class class, which does exactly the same (as the operator, not your method), and can be used in the stream.

2021-01-07 12:22 UTC, LucasBulczak commented on src/test/java/com/epam/prejap/tetris/block/JBlockTest.java
> +        softAssert.assertTrue(actualRows == expectedImage.length);
VERY good note - thanks!

2021-01-07 12:23 UTC, LucasBulczak commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +                .anyMatch(this::isInstanceOf);
:-)

2021-01-07 12:24 UTC, LucasBulczak commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +}
Thanks to Pawel ;-)

2021-01-07 12:25 UTC, LucasBulczak commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        return e.getClass().getSimpleName().equals(blockClassName);
I can't fix this before work - I'll do it when I get back :-(

2021-01-07 19:03 UTC, TJB4epam commented
Also, do remember to bump up the minor version number. This ain't Tetris 0.1 no longer. See to it in the POM file.

2021-01-07 19:04 UTC, pkierat-epam commented
Tests are failing.
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@6fdb1f78
Tests run: 19, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.436 sec <<< FAILURE!
shallContainLBlock(com.epam.prejap.tetris.block.BlockFeedTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertTrue(Assert.java:45)
        at org.testng.Assert.assertTrue(Assert.java:55)
        at com.epam.prejap.tetris.block.BlockFeedTest.shallContainLBlock(BlockFeedTest.java:30)


Results :

Failed tests:   shallContainLBlock(com.epam.prejap.tetris.block.BlockFeedTest): expected [true] but found [false]

Tests run: 19, Failures: 1, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.823 s
[INFO] Finished at: 2021-01-07T20:02:51+01:00
[INFO] ------------------------------------------------------------------------
```

2021-01-07 22:33 UTC, LucasBulczak commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +        return e.getClass().getSimpleName().equals(blockClassName);
@pkierat-epam, Thank you with all my heart for this tip!
@TJB4epam, I think I know what the purpose of your question was. I have to think about what I want to get, not just code, code and code ;-)

2021-01-07 22:36 UTC, LucasBulczak commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTestFactory.java
> +public class BlockFeedTestFactory {
I had a problem writing it in a way that would work and I liked it at the same time ;-) I believe now it will be ok.

2021-01-08 00:04 UTC, LucasBulczak commented
> Tests are failing.

I have to admit that I spent quite a lot of time on it and I can't say why it is so now, but:
1. Running tests from testng.xml works fine.
2. Invoking tests from the console (mvn test) does not work with the following result:

```java
Łukasz@DESKTOP-3D5AO4V MINGW64 ~/Documents/dev/code/tetris (master)
$ mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< com.epam.prejap:tetris >-----------------------
[INFO] Building tetris 0.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tetris ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Łukasz\Documents\dev\code\tetris\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ tetris ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to C:\Users\Łukasz\Documents\dev\code\tetris\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tetris ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ tetris ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to C:\Users\Łukasz\Documents\dev\code\tetris\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ tetris ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[ERROR]
An error occurred while instantiating class com.epam.prejap.tetris.block.BlockFeedTest. Check to make sure it can be instantiated
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.655 s
[INFO] Finished at: 2021-01-08T00:49:05+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project tetris: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Łukasz\Documents\dev\code\tetris\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR]
[ERROR] An error occurred while instantiating class com.epam.prejap.tetris.block.BlockFeedTest. Check to make sure it can be instantiated
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR]
[ERROR] An error occurred while instantiating class com.epam.prejap.tetris.block.BlockFeedTest. Check to make sure it can be instantiated
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:733)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I could really use some help with this...

2021-01-08 14:31 UTC, pkierat-epam commented
That is because Maven doesn't know that it should run tests using testng.xml and searches the classpath instead. Try adding this to the pom:
```xml
<configuration>
  <suiteXmlFiles>
    src/test/resources/testng.xml
  </suiteXmlFiles>
</configuration>
```

2021-01-08 15:30 UTC, LucasBulczak commented
Thanks a lot! I will do it immediately after work!

2021-01-08 21:21 UTC, LucasBulczak commented
@TJB4epam, @pkierat-epam 
Thanks a lot for all the help! I have implemented all your recommendations and resolved any conflicts. I am ready for another check :-)

2021-01-09 07:29 UTC, TJB4epam commented on pom.xml
> +                <version>${version.plugin.maven.surefire}</version>
Welp. Pending review was pending and not seen by anyone. Disregard now. Paweł already gave you a hint here and you followed it.

2021-01-09 10:19 UTC, LucasBulczak commented on pom.xml
> +        <project.java.version>14</project.java.version>
I am just trying to use what you have taught us :-)

2021-01-09 10:24 UTC, LucasBulczak commented on pom.xml
> +                <version>${version.plugin.maven.surefire}</version>
I knew there was something else about your earlier question! It is a pity I did not get it then ;-)

2021-01-09 10:34 UTC, LucasBulczak commented on src/main/java/com/epam/prejap/tetris/block/JBlock.java
> + * The JBlock class represents "J" shaped block in tetris game.
Right, thanks.

2021-01-09 10:39 UTC, LucasBulczak commented
Taking this opportunity - after resolving all your comments, should we point to you in a message eg. " @TJB4epam , everything is ready for another verification", or are you getting any automatic info?

Because I wouldn't like to overflow your mailbox :-)

2021-01-11 06:49 UTC, pkierat-epam requested changes
Minor fixes and I think we're good to go (if nothing else goes first :wink: ).

2021-01-11 06:49 UTC, pkierat-epam commented on pom.xml
> +    <groupId>com.epam.prejap</groupId>
Why did `groupId` go here? Not that it matters for the semantics of POM, but:
1. usually the tags are in the order: groupId, artifactId. I did a quick search across 2000+ poms in my local repo and I couldn't find the tags in reversed order.
2. it's gonna generate unnecessary conflicts.

2021-01-11 06:49 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/block/BlockFeed.java
> +        OBlock::new, LBlock::new, JBlock::new, IBlock::new
The same question that was asked in one of the previous PRs: why in the middle? Usually new changes are added at the end.

2021-01-11 06:49 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockFeedTest.java
> +                .anyMatch(blockChildClass::isInstance);
:+1:

2021-01-11 06:49 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/OBlockTest.java
> +}
EOF :raised_eyebrow:

2021-01-11 10:15 UTC, LucasBulczak commented on src/main/java/com/epam/prejap/tetris/block/BlockFeed.java
> +        OBlock::new, LBlock::new, JBlock::new, IBlock::new
Because of conflict resolution - my mistake ;-)

2021-01-11 10:15 UTC, LucasBulczak commented on pom.xml
> +    <groupId>com.epam.prejap</groupId>
My mistake :-)

2021-01-11 10:19 UTC, LucasBulczak commented
@pkierat-epam fixed :-)

2021-01-11 20:23 UTC, pkierat-epam commented
All requirements met. Merging.
Points: 35

2021-01-11 20:24 UTC, merged

2021-01-12 05:15 UTC, LucasBulczak commented
A brief summary of my mistakes and what I have learned:
1. JavaDoc for methods that are part of the public API -> Interface / abstract class.
2. If something needs further explanation, JavaDoc is a good place to go.
3. Use proper words ;-)
4. After each merge put your part at the end -> it will be easier for others to make theirs.
5. Do not reinvent the wheel -> check if the function you want to write is not already present ;-)
6. Add messages in tests, this can be really helpful -> soft assertions can have them too.
7. Bump up the minor version number ;-)
8. Use for what you have learned.
9. EOF.
10. If you do not know something -> look for it. If you do not find it -> show what you have learned and ask.
11. Talk to colleagues, they can help you or guide you.

Thanks, it is now time to review the whole thing and make more changes :-D