16 elapsed time is presented
EPAM-Online-Courses/tetris pull request #24
Opened 2021-01-06 19:07 UTC by WiktoriaMajchrzak

Hello, @pkierat-epam!
I've added Timer class to track elapsed time and modified Printer class to display it. 
Please review.

2021-01-06 19:40 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        Timer timer = playfield.getTimer();
If timer is a dependency of Playfield, is the main loop a good place to make use of it?

2021-01-06 19:40 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> +    public void setStartTime(Instant startTime) {
Why use setters and not allow the timer to manage its internal state? A more object-oriented way would be to have a method that performs a tick (and the timer should know what to do with it).

2021-01-06 19:40 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> +            throw new TetrisException("Start time is not set");
The situation here is actually an example of illegal state, and there happens to be a ready, multi-purpose exception for it in JDK.

2021-01-06 19:40 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public Playfield(int rows, int cols, BlockFeed feed, Printer printer, Timer timer) {
If you think about it, printing the time turns out to be completely independent of the Playfield functionality. Instead, the time is initialized at the beginning of the game, and then printed on every redraw of the board, using an internal state of the Timer. So maybe it should actually be a dependency of Printer?

2021-01-06 21:17 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        Timer timer = playfield.getTimer();
Timer dependency was moved to Printer and Tetris classes.

2021-01-06 21:18 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> +    public void setStartTime(Instant startTime) {
Internal state was encapsulated.

2021-01-06 21:19 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> +            throw new TetrisException("Start time is not set");
TetrisException has been removed.

2021-01-06 21:19 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public Playfield(int rows, int cols, BlockFeed feed, Printer printer, Timer timer) {
Timer dependency has been moved to Printer and Tetris classes.

2021-01-06 21:21 UTC, WiktoriaMajchrzak commented
@pkierat-epam, I've implemented your suggestions :)
Please review.

2021-01-06 23:33 UTC, TJB4epam commented
I've just merged other changes. Make sure you have all you need and that this works after you merge the new master. GitHub for one reports conflicts in the Tetris file.

2021-01-06 23:53 UTC, WiktoriaMajchrzak commented
@TJB4epam, the conflict has been resolved.

2021-01-07 00:57 UTC, TJB4epam requested changes

2021-01-07 00:57 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> +    public Duration getElapsedDuration() {
So - either change the name or change the method.

2021-01-07 00:57 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +    public void headerShouldPrintValidHeaderWithTimeInSeconds() {
1. Why no DataProvider? All those tests can easily be parametrized.
2. You are testing TIME here, right? So, a question - how LONG will those tests run? Like, if there are 20 people working on this code, and they will run the tests 10 times a day each, how many extra seconds will these tests take?
3. Have you taken a look at Clock class? It was introduced to treat time as a dependency.
4. No GWT structure in your tests?
5. For a unit test - what is the purpose of those tests - to see if printing works or timing? Remember: FIRST.
Links:

1. https://blog.indrek.io/articles/unit-testing-classes-that-depend-on-time/
2. https://docs.oracle.com/javase/8/docs/api/java/time/Clock.html
3. https://capgemini.github.io/development/testing-timers/ 
4. https://stackoverflow.com/questions/27067049/unit-testing-a-class-with-a-java-8-clock

2021-01-07 15:36 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> + * <br><br>
The paragraphs have been added.

2021-01-07 15:36 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> + * {@link Timer} class is responsible for calculating elapsed time.
JD has been corrected.

2021-01-07 15:37 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> + * <br><br>
JD has been corrected.

2021-01-07 15:37 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> +     * Method is responsible for calculating duration by multiplying ticks and game delay.
JD has been corrected.

2021-01-07 15:37 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> + * The class includes methods for counting ticks ({@link Timer#tick}) and calculating elapsed time ({@link Timer#getElapsedDuration}).
The method name has been changed from getElapsedTime to calculateElapsedTime.

2021-01-07 15:38 UTC, WiktoriaMajchrzak commented on src/main/java/com/epam/prejap/tetris/game/Timer.java
> +    public Duration getElapsedDuration() {
The method name has been changed from getElapsedTime to calculateElapsedTime.

2021-01-07 15:39 UTC, WiktoriaMajchrzak commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +    public void headerShouldPrintValidHeaderWithTimeInSeconds() {
1. DataProviders have been added.
4. GWT commens have been added.
2, 3, 5.  As per Paweł's suggestion I switched from calculating elapsed time by calculating a difference of two Instants to counting ticks (time delays in main game loop).
Thanks to this I don't need to use Clock class. The tests also do not take unnecessary time as tick counting is almost instantaneous.
TimerTest tests are meant to verify that elapsed time is calculated correctly and PrinterTest tests are to verify that this time is being printed correctly (with regards to required format).

2021-01-07 15:41 UTC, WiktoriaMajchrzak commented
@TJB4epam, I've implemented your suggestions.
Please review.

2021-01-07 19:48 UTC, TJB4epam requested changes
Please, also bump the POM version. One minor version should go up: from 0.1 to 0.2, or from 0.4 to 0.5 (I don't recall what's the version number ATM, I think it's 0.1).

2021-01-07 19:48 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +        for (int i = 0; i < cycles; i++) {
This is not when, this is given. When is your `header` call.

2021-01-07 19:48 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +        printer.draw(emptyGrid);
This is not when, this is given. When is your `draw` call.

2021-01-07 19:48 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +        printer.draw(emptyGrid);
What's the gain in having 2 identical tests? If you are after checking that draw calls header, there are simpler ways: `Mockito.verify`, for one.

2021-01-07 19:48 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TimerTest.java
> +    public void shouldThrowIllegalArgumentExceptionForInvalidTickDuration(int tickDurationInMillis) {
Good of you to have thought about that.

2021-01-07 19:48 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TimerTest.java
> +                                          int expectedSecondsDuration,
I don't really like calling 3 ints together and calling one int an hour, another a minute and yet another a second. I'd prefer having a `Time` object - preferably an existing class from JDK8 DateTime API. That way things are much cleaner. And we have API to calculate between hours / millis, etc., like TimeUnit enum or methods on DateTime API classes.

2021-01-07 19:48 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TimerTest.java
> +    public Object[][] getValidData() {
A very vague and generic name. Every single data provider can be called like that. Or, like the one below that gets invalid data. 

Data provider: I'm getting a very crucial data, that fulfills 17 special purposes and doesn't break any law in question, and that means 21 laws! 
Naming authority, like the author of this code: So, it's valid data? 
Data provider, beaten: Yeah.

;-)

2021-01-07 19:48 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TimerTest.java
> +public class TimerTest {
Please, remember to add test groups, add your tests to testng.xml suite in a way that allows to run ONLY your tests and allows to run your tests AND all others. Applies to BOTH test classes!

2021-01-07 19:48 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TimerTest.java
> +                {60000, 60, 0, 0, 1},
Java - since version 7 - allows to use _ as a part of a numeric literal, like: 7_000 or 60_000. This greatly improves readability. Here it's a minor thing, in the PrinterTests however that would be a welcome improvement. This comment however you don't need to follow.

2021-01-08 10:12 UTC, WiktoriaMajchrzak commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +        for (int i = 0; i < cycles; i++) {
Marking has been corrected.

2021-01-08 10:12 UTC, WiktoriaMajchrzak commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +        printer.draw(emptyGrid);
Marking has been corrected.
Mockito.verity has been added.

2021-01-08 10:12 UTC, WiktoriaMajchrzak commented on src/test/java/com/epam/prejap/tetris/game/TimerTest.java
> +                                          int expectedSecondsDuration,
Ints have been replaced by one String.

2021-01-08 10:12 UTC, WiktoriaMajchrzak commented on src/test/java/com/epam/prejap/tetris/game/TimerTest.java
> +    public Object[][] getValidData() {
Tha DataProviders names have been changed.

2021-01-08 10:13 UTC, WiktoriaMajchrzak commented on src/test/java/com/epam/prejap/tetris/game/TimerTest.java
> +public class TimerTest {
The test gropus have been added.

2021-01-08 10:13 UTC, WiktoriaMajchrzak commented on src/test/java/com/epam/prejap/tetris/game/TimerTest.java
> +                {60000, 60, 0, 0, 1},
The readability of large numbers has been improved.

2021-01-08 10:14 UTC, WiktoriaMajchrzak commented
@TJB4epam, all suggestions have been corrected :)
Please review.

2021-01-08 14:46 UTC, pkierat-epam commented on src/test/resources/testng.xml
>  </suite>
And the famous EOF...

2021-01-08 15:03 UTC, merged

2021-01-08 15:03 UTC, pkierat-epam commented
Points: 30
Congratulations!