10 points are presented on every change
EPAM-Online-Courses/tetris pull request #25
Opened 2021-01-06 19:39 UTC by PaulinaKsienzyk

@pkierat-epam 
I had to display the current score and update in every cycle.  
I thought that instead of displaying the points in play(), I would add the current score in Playfield.
Scoring is done as before - for the block placed. However, it can be updated in the future, e.g. depending on the number of rows removed.

2021-01-06 23:33 UTC, TJB4epam commented
I've just merged other changes. Make sure you have all you need and that this works after you merge the new master. GitHub for one reports conflicts in the testng.xml file.

2021-01-07 06:33 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        originalPrintStream = System.out;
It's a common practice in projects to speed up test execution by running tests in parallel (several threads, each running different set of tests). Capturing global output (`System.out`) may cause serious problems here, since you can get mixed output from different test cases, which makes your tests unpredictable and unreliable. A better approach is to allow the output to be substituted separately for each instance. (More on that in a moment.)

2021-01-07 06:33 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        Printer printer = new Printer(System.out);
`Printer` accepts an instance of the `PrintStream` class which acts as a wrapper for other output streams, for example, ByteArrayOutputStream you use in the `setUpStreams()` method. While I/O is still ahead of us, you can try it now and capture the output locally instead of setting the global variable.

2021-01-07 06:33 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        updateScore();
Should counting score be a responsibility of Playfield? What about SRP?

2021-01-07 11:17 UTC, TJB4epam requested changes
Per Paweł's remarks.

2021-01-07 17:11 UTC, PaulinaKsienzyk commented
@pkierat-epam 
Conflicts has been resolved. 

Follow your advice instead of capturing global System.out, 
each instance of Playfield has a separate output stream.

2021-01-07 19:51 UTC, TJB4epam commented
> @pkierat-epam
> Conflicts has been resolved.
> 
> Follow your advice instead of capturing global System.out,

:D:D:D:D:D That's hillarious. I'll laugh at Paweł, that he was told off and ordered to follow his own advice. :D 

Just messing with you here a bit, I know that it was a simple typo. :-)

2021-01-07 19:56 UTC, PaulinaKsienzyk commented
@TJB4epam You made my day! :D Or I made it hm? :D Sorry for typo @pkierat-epam, 
I will post the corrected code in a moment and I do not know if I will laugh anymore :)

2021-01-07 19:58 UTC, TJB4epam reviewed
Publishing review as new changes came in - will re-review. :sad-panda:

2021-01-07 19:58 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        updateScore();
Bumping the thread as I'm also interested in your answer @PaulinaKsienzyk

2021-01-07 19:58 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +     * Returns current number of points awarded
Nice of you to add a JD, but for common get/set methods one doesn't. Idea behind is these are dead simple and therefore JD for'em is useless.

Also: why such short lines? Less than 50 characters AND already a line-break? Was this coded on a mobile phone?

2021-01-07 19:58 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +import java.util.regex.Pattern;
Mmmm. A regex. :a knowing smile:

2021-01-07 19:58 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        updateScore();
Found the answer published - for some reason - in another thread. Pasting it here:

> Right - Playfield's updating of the score breaks the SRP rule, so I'm getting down to work.

2021-01-07 20:10 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +     * Returns current number of points awarded
@TJB4epam Ok, I'm already deleting. 
Regarding short lines - I thought for better readability. Thanks for note:)

2021-01-07 20:31 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        updateScore();
I added a Referee class to award points. which relieves Playfield from responsibility for updating the score

2021-01-07 20:42 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        originalPrintStream = System.out;
I wrote everything in another thread like @TJB4epam noticed so: 
instead of capturing global System.out, each instance of Playfield has a separate output stream.

2021-01-07 20:47 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        Printer printer = new Printer(System.out);
I set up streams inside each method, because I read that BeforeMethod annotation seems broken with groups.

2021-01-07 20:56 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        updateScore();
Referee class is simple, but I have already idea about removing full lines and awarding points for removed rows

2021-01-09 07:45 UTC, TJB4epam requested changes
Publishing a review that was left pending. Sorry about the delay.

2021-01-09 13:17 UTC, PaulinaKsienzyk commented on src/test/resources/testng.xml
> +                <include name="score"/>
Sorry for my negligence. Already corrected.

2021-01-09 13:18 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        System.setOut(originalPrintStream);
I got rid of System.out in a test environment.

2021-01-09 13:19 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        if (!Pattern.compile(SCORE_REGEX).matcher(actualString).find()) {
I compiled the pattern before the tests in group.

2021-01-09 13:20 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +            fail();
I replaced this with assertTrue.

2021-01-09 13:21 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        if (!Pattern.compile(SCORE_REGEX).matcher(actualString).find()) {
I replaced this with assertTrue.

2021-01-09 13:33 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        Playfield playfield = createSamplePlayfieldWithOutput(System.out);
@TJB4epam 
At the moment I just used myPrintStream in this case as well. 
I see Wiktoria uses mockito in her tests. So far I haven't used it so it's a good opportunity to get to know this tool.
Shall I also use it?

2021-01-12 13:38 UTC, pkierat-epam requested changes
Apart from the notes below, please pull master, resolve conflicts and bump up the pom version.

2021-01-12 13:38 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        System.setOut(myPrintStream);
This is still risky. (AFAIR, it was mentioned somewhere already.) Moreover, from what I see, this particular line is not necessary anymore (unless you plan to capture output that doesn't go through the Printer class, which actually shouldn't happen).

2021-01-12 13:38 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        referee = new Referee();
Nice idea with the referee. It might help develop more advanced scoring in the future :) Therefore, it might be useful to provide it as a dependency for the play field (i.e. inject through the constructor), so that we can test the playfield more reliably.

2021-01-12 13:38 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        setUpStreams();
If the `setUpStreams()` returned the fake output stream (instead of setting it in a field), you wouldn't need to reset it in every test.

2021-01-12 13:38 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        return new Score(playfield.getScore());
With a referee provided externally (i.e. not an internal component of `Playfield`), you can take the score from it, not from the playfield.

2021-01-12 13:42 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        Playfield playfield = createSamplePlayfieldWithOutput(System.out);
Mockito is not necessary here, but feel free to try it out (it will probably increase the implementation time for this issue though).

2021-01-12 16:04 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        Playfield playfield = createSamplePlayfieldWithOutput(System.out);
Ok , then I will make all the changes and, if possible (after all the deadline is tomorrow:) ) , I'll try to improve solution using mockito (I already read a bit but I don't quite understand the diferrences beetwen spy() and mock() - when to use particular method, but that's separate topic :).

2021-01-12 21:08 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        System.setOut(myPrintStream);
Deleted reassigning the standard output stream.

2021-01-12 21:24 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        setUpStreams();
I changed it to set up streams once before the group tests.

2021-01-13 09:22 UTC, TJB4epam requested changes
I concur with Paweł - Referee should hold the score and adjusting it should be his job. If you wish to do it really well, perhaps an Observer pattern between Referee and Playfield would be handy (that definitely can eliminate getScore from the Playfield). 

Other comments placed where they are applicable.

BTW: looks way better than initially!

2021-01-13 09:22 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    @BeforeGroups(groups = "Score")
Thank you

2021-01-13 09:22 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    @Test(groups = "Score")
Thank you.

2021-01-13 09:22 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        System.setOut(myPrintStream);
Please push out new changes - the version of the code that I see has the setOut method used still.

2021-01-13 09:22 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        setUpStreams();
OK, please push out the version with it - here I see it in a test, not once before test. Though perhaps that's only UI.

2021-01-13 13:43 UTC, PaulinaKsienzyk commented on pom.xml
> +    <version>0.6</version>
Thank you, now is up-to date.

2021-01-13 13:46 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        System.setOut(myPrintStream);
Changes pushed. SetOut is not in this version, I give you my word :)

2021-01-13 13:51 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        setUpStreams();
Changes pushed. Now is one setUp method before the group tests. Also I deleted unnecessary parameter to create sample Playfield, because I'm using only myPrintStream .

2021-01-13 13:58 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        referee = new Referee();
Dependency injection done.

2021-01-13 14:02 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        return new Score(playfield.getScore());
Ok, now I'm thinking about how to fix this properly (as far as encapsulation is concerned). If I want to know what is the current number of points in the Tetris class, I have to change the Referee to the public one ( I have now), but is there no other option (I'm thinking  out loud)?  
Now in the play() method I gave Referee as a parameter to get the current score.
I will try to change it, so I am not submitting for a review yet.

2021-01-13 14:04 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Referee.java
> +class Referee {
I will copy what I wrote to Paweł Kierat:

> Ok, now I'm thinking about how to fix this properly (as far as encapsulation is concerned). If I want to know what is the current number of points in the Tetris class, I have to change the Referee to the public one ( I have now), but is there no other option (I'm thinking out loud)?
Now in the play() method I gave Referee as a parameter to get the current score.
I will try to change it, so I am not submitting for a review yet.

2021-01-13 14:06 UTC, PaulinaKsienzyk commented on pom.xml
> +    <version>0.6</version>
Project version bumped up.

2021-01-13 14:38 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public int getScore() {
@TJB4epam I understand what you mean by that, 
I just don't know how to get out of it yet :) This is the method of the Referee class now, so I made the whole Referee class public... (To use it in the play() method)
In the current design we want to return the current score at the end of the game and wrap it in Score. 
So if the game is over, the referee should give the actual number of points. Should I change the name of the method e.g giveFinalScore?

2021-01-13 16:57 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public int getScore() {
@TJB4epam After thinking about the goal of the Referee class and current points, I think maybe it would be better to include the Score class in the game package. I would then keep the encapsulation and there would be no need to use temporary points as public. The Referee could return the total score as a Score.

2021-01-13 17:02 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public int getScore() {
Oh, but now I read the comments on "11 implement game speed increase" and I see that there is new package for Score.

2021-01-13 19:01 UTC, PaulinaKsienzyk commented
@TJB4epam or @pkierat-epam  All requested changes applied.  

I applied the Observer Pattern, which Tomasz advised me to notify Referee about the change in Playfield, i.e. when a new block will appear, to award additional points. I changed the Referee class to public so that the number of points could be returned in the play method. However, I know that the actual number of points is really needed to display it. My thought was to make the Score class public and create a method in Referee totalScore that would return the wrapped result, then the currentScore method would package-private. I saw that Uladzislau had an idea to change this class to a public one and transfer it to another package, so I will stay here for now. If there are any objections, I will be grateful for the response.

2021-01-13 20:17 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        return new Score(playfield.getScore());
Changed to taking score from Referee.

2021-01-14 11:17 UTC, TJB4epam commented
Despite the conflicts I'll review to push it to closing faster. Ofc fixing conflicts MUST happen prior to merges.

2021-01-14 11:31 UTC, PaulinaKsienzyk commented
@TJB4epam 

> Despite the conflicts I'll review to push it to closing faster. Ofc fixing conflicts MUST happen prior to merges.

I can see now that I am doing it wrong. I'll fix it.

2021-01-14 11:43 UTC, TJB4epam requested changes

2021-01-14 11:43 UTC, TJB4epam commented on pom.xml
> +    <version>0.9</version>
One more bump after latest merges.

2021-01-14 11:43 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/PlayfieldObserver.java
> +public interface PlayfieldObserver {
No Javadoc on a public interface of such importance / novelty?

2021-01-14 11:43 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Referee.java
> +    public int currentScore() {
If this would be done via toString...?

2021-01-14 11:43 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public Playfield(BlockFeed feed, Printer printer, Grid grid, Referee referee) {
Again: dependency injection.

I'd rather have `List.of(referee)` passed as a parameter to a c-tor call for Playfield. That way later we don't need to change the c-tor, just add a param to the list. 

As little logic in the c-tors as possible, ideal c-tors just assign params to fields.

2021-01-14 11:43 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    private void notifyBlockObservers() {
Well done.

2021-01-14 11:43 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
>  public class Playfield {
Usually the observed class has a contract as well, but for speed's sake I'll let that slide this time.

2021-01-14 11:43 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        printer.printScore(referee.currentScore());
For the sake of printing it would be better to pass a referee and call toString on it, right?

2021-01-14 11:43 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Referee.java
> +public class Referee implements PlayfieldObserver {
As it is now - it's a good candidate for a record with one field. Just FYI.

2021-01-14 11:43 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    public void scoreShouldBeDisplayedWhenNewBlockAppears() {
Perhaps "shouldDisplayScoreUponFirstBlockAppearing" as name? Highlights the case of this being not a new block but a first block?

2021-01-14 11:43 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/RefereeTest.java
> +        int expectedScore = 1;
Not that I mind this being 1 and having a `++` in the Referee class, but the title of the PR says "10 points ... every change". Mind clearing that up?

2021-01-14 11:43 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        return new Score(referee.currentScore());
Excellent. These two are now tied. My question to the author: in terms of SRP and DRY how these two classes differ?

2021-01-14 11:43 UTC, TJB4epam commented on pom.xml
> +    <version>1.0</version>
Good!

2021-01-14 11:43 UTC, TJB4epam commented on pom.xml
> +    <version>0.9</version>
And bumped it was.

2021-01-14 11:45 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        originalPrintStream = System.out;
Changed later - resolving.

2021-01-14 11:45 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        Printer printer = new Printer(System.out);
Changed later - resolving.

2021-01-14 11:46 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        updateScore();
See comments on Referee and where it's tied to score. Resolving this discussion.

2021-01-14 11:48 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        referee = new Referee();
With introduction of the observer pattern this has slipepd a bit - list dependency is still a dependency. Just FYI. Resolving this, the issue is marked elsewhere in a separate thread and a referee dependency is resolved still.

2021-01-14 12:16 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/RefereeTest.java
> +        int expectedScore = 1;
10 is the issue number, but I had to check it, because that's what it sounds like :)

2021-01-14 12:35 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public int getScore() {
Worry not about that. Uladek - judging by how he started - can improve over what we have here. Also, he's 2nd in line.

2021-01-14 12:36 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public int getScore() {
The point of this comment was to point out OOP practice - encapsulation. Your answer is to deencapsulate - make the class public. I'll resolve this for now and instead - let's think about that in the discussion on Referee and Score.

2021-01-14 13:34 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/PlayfieldObserver.java
> +public interface PlayfieldObserver {
JavaDoc added.

2021-01-14 13:35 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Referee.java
> +    public int currentScore() {
Done using toString(). 
I also used the display of points directly in the Printer class as it is done in the case of time

2021-01-14 13:38 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public Playfield(BlockFeed feed, Printer printer, Grid grid, Referee referee) {
Yes, it hurt the eyes. Now I'm passing list of playfield observators through the constructor. Now it is the only dependcy on the Referee class.

2021-01-14 13:38 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/game/Referee.java
> +public class Referee implements PlayfieldObserver {
Thank you

2021-01-14 13:40 UTC, PaulinaKsienzyk commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    public void scoreShouldBeDisplayedWhenNewBlockAppears() {
Test renamed

2021-01-14 13:42 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        return new Score(referee.currentScore());
Exactly! I tried to tie them all the time, and these are two different responsibilities... 
After all, the Referee is about keeping the current result. 
I changed it as it was, it is a separate task to do.

2021-01-14 14:40 UTC, PaulinaKsienzyk commented
@TJB4epam
I applied the required changes.
the list of observers is passed by the constructor, Referee meets the SRP rule, 
displaying the result is similar to displaying the time with the Printer class using Referee dependency.
Hope it looks so much better. 
Also I bumped up project version to 1.1. 
Thank you for all your comments and for your time, I've learned soooo much.

2021-01-14 15:11 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        return new Score(referee.currentScore());
I changed it to the previous solution. Score class is for storing the result, mine is to change it

2021-01-14 17:39 UTC, PaulinaKsienzyk commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        return new Score(referee.currentScore());
I added referee in the Tetris constructor like the Timer is. Then I got total points and put it to the new Score.

2021-01-14 18:25 UTC, pkierat-epam requested changes

2021-01-14 18:25 UTC, pkierat-epam commented on pom.xml
> +        <project.java.version>15</project.java.version>
This is not necessary, since in Java 15, records are still in preview (to become standard in Java 16). Moreover, with only that change, the build will fail, because you need to enable the preview features. Try adding that instead:
```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <compilerArgs>
            <arg>--enable-preview</arg>
          </compilerArgs>
        </configuration>
      </plugin>
```

2021-01-14 19:14 UTC, PaulinaKsienzyk commented on pom.xml
> +        <project.java.version>15</project.java.version>
@pkierat-epam Ok, done. Thank you

2021-01-14 19:57 UTC, pkierat-epam commented on pom.xml
> +    <version>1.1</version>
```suggestion
    <version>0.11</version>
```
It's not a general rule that the the minor version number overflows at 10 and causes increase of the major number. Some projects do that, but many don't, and it's rather an explicit decision of the team.

2021-01-14 20:01 UTC, pkierat-epam commented
Looks good. Merging. (Points to be added later.)

2021-01-14 20:01 UTC, merged