15 implement random obstacles
EPAM-Online-Courses/tetris pull request #28
Opened 2021-01-07 12:26 UTC by BrendanAW

Extra blocks added based off size of playfield

2021-01-07 20:20 UTC, TJB4epam commented
I love the smell of conflicts in the evening, when I'm finding out that... no need to review! ;-P

Or, in other words: please fix the conflicts first.

2021-01-09 08:30 UTC, TJB4epam requested changes

2021-01-09 08:30 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        IntStream.rangeClosed(0, starterBlockAmt).forEach(i -> addStarterBlocks());
Logic in a c-tor is a smell. Here, we have 'n' calls to a method FROM a c-tor. How to test that method then? 
How to test that Playfield was initialized well? All Playfield initialization calls will now also execute 'n' calls to `addStarterBlocks`? Why can't initialization of a starter block set happen outside of this class?

2021-01-09 08:30 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    public final int starterBlockAmt;
Public final because?

2021-01-09 08:30 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +     * @param isStarterBlocks determines how many blocks Playfield will start with
A boolean is unable to do that due to having 2 possible values which do not match the "how many" :-)

2021-01-09 08:30 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +    private void addStarterBlocks() {
I'm still not certain why Playfield. It was a fairly large class already and it had a defined responsibility. Don't you think you're breaking SRP here? Randomizing a set of blocks could well be done outside, with just the result passed in?

I'm looking forward to you testing how large area may be taken by the results of this random placement of random blocks. :sinister-grin: You know, to make sure you're not taking too much space from the player.

2021-01-09 08:30 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +     * @param isStarterBlocks determines how many blocks Playfield will start with
At least not with `Math.random()*rows/2 +1` involved.

2021-01-09 08:30 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/ExtraBlocksTest.java
> +    int rows = 10;
Why are all fields package-private?

2021-01-09 08:30 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/ExtraBlocksTest.java
> +        assertEquals("PlayField generated without starter blocks, should return 0", 0, p1.starterBlockAmt);
Were tests the reason for this field being PUBLIC? If so, why not package-private?

2021-01-09 08:30 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/ExtraBlocksTest.java
> +        assertEquals("PlayField generated without starter blocks, should return 0", 0, p1.starterBlockAmt);
And even better, why not injected via c-tor?

2021-01-09 08:30 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/ExtraBlocksTest.java
> +}
You don't plan on having any tests making sure that some block won't take too large a space? No tests that see how this works with different playfields? If I give a mini-playfield, won't this take too much space?

2021-01-11 09:51 UTC, pkierat-epam commented
You made a significant extraction of of the Playfield's logic into a separate component, which is awesome, but... you only provided a test for the Grid class. How do you ensure that the Playfield class works correctly after the refactor?

2021-01-11 10:02 UTC, pkierat-epam requested changes

2021-01-11 10:02 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/game/GridTest.java
> +        grid = new Grid(feed, rows, cols);
From what I've seen so far, you always need to do two things:

1. invoke the constructor,
2. call the `generateGrid` (which changes the sate of the grid).

For me, it's a perfect opportunity to try a factory method (or even a factory class) that returns an object which is ready to use.

2021-01-12 08:27 UTC, pkierat-epam commented
You know, it's a good practice to at least respond somehow to the remarks posted in the code review... "fixed", "done", or simple :+1: would do.

2021-01-12 11:23 UTC, BrendanAW commented
@pkierat-epam, Sorry I wasn't sure if I should do that here or not

2021-01-12 20:12 UTC, pkierat-epam requested changes

2021-01-12 20:12 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/game/GridTest.java
> +        assertEquals(count, ((rows - block.rows() + 1) * (cols - block.cols() + 1)), "Count should be equal to calculated potential moves");
> `((rows - block.rows() + 1) * (cols - block.cols() + 1))`

This expression is:
1. repeated few lines below,
2. unclear.

Maybe a method extraction and a human-readable name would help?

2021-01-12 20:12 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        var flagPresent = Arrays.asList(args).contains("-rb");
Now, imagine more and more people are adding their options here. (There is at least one person that has something to add.) I'm gonna leave it for now, counting that others will figure out a decent way to work it out.

In case you're interested, there's a nice library called JCommander which helps with parsing command-line options quite nicely.

2021-01-13 08:12 UTC, BrendanAW commented
@pkierat-epam, The tests have been updated, although I'm uncertain about JCommander, to use it, should I make a zero-arg constructor? If we are to  be parsing the main args this way, would a separate main class not be a better approach? Finally if Martyna's code has already been approved, should I just add a method to check for my flag within her class?

2021-01-13 11:11 UTC, TJB4epam requested changes
New PR hast just been merged. Frankly, this is the next item on my list, and I'd have merged it already if you had bumped the POM version and added more Javadocs. I can live without JDs, but bumping the POM is required. Also - refresh your base here, master has changed.

2021-01-13 16:21 UTC, BrendanAW commented
@TJB4epam, merging causes an error that I would like to know how to address. The master's changes are configured to check the main args for navigation keys, but if navigation keys are not present and my flag is, it throws an error stopping the program, can I change the class methods to resolve this, or should I simply add logic to work around the checkArgsForNavigationKeys method from being called?

2021-01-13 16:53 UTC, BrendanAW commented
@TJB4epam, I fixed the main method the simple way, added a javadoc for Grid and upped the version by 0.1

2021-01-14 07:00 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/game/Grid.java
> +    public static Grid getNewGrid(BlockFeed feed, int rows, int cols, boolean addExtraBlocks) {
For future:

Altering the behavior of the method with a boolean flag is usually a symptom of SRP violation (two methods merged into one).

One way to avoid it is to have more than one Grid implementation: a base one (which wouldn't require a feed), and another one extending it with the random blocks... Oh wait, inheritance is prohibited ;-)

So another option is to use the Strategy pattern to pass extra behavior as an argument depending on the '-rb' flag.

2021-01-14 09:56 UTC, BrendanAW commented
@pkierat-epam, alright I'm looking into what you mentioned but as of now, my code can be merged, as it works appropriately

2021-01-14 10:44 UTC, pkierat-epam commented
Merging.
Points: 125

2021-01-14 10:44 UTC, merged

2021-01-14 10:46 UTC, TJB4epam approved these changes