12 every block has different color #12
EPAM-Online-Courses/tetris pull request #34
Opened 2021-01-09 11:40 UTC by dominikjaniga91

Hi, @pkierat-epam @TJB4epam I've made a solution to issue #12. 

The current solution picks an appropriate color from enum Color base on an instance of the block. There is a bunch of if-else and instanceof in ColorPicker class which does not look good in my opinion so here's the question: Can I add the color field to every block class? Alternatively, I can create a Map<Block, Color> but this still requires changes in block classes (override equals).

Returned color is an identifier from a code from ANSI escape code. Id is set up to the game's grid. Since there is a field colorId in the Playfield class I decided to remove the dot parameter from the act() in the BringAction interface.

I decided to change the game's block sing from '#' to empty string because paint method color a background. Such a block looks a little bit better:

![image](https://user-images.githubusercontent.com/57048349/104090164-e6fdaa80-5274-11eb-9389-0a6d93aa5835.png)

A question about tests. Jacoco shows that I did not cover the test for Painter class which is utility class, is it a normal behavior of that plugin? can I change that somehow?

![image](https://user-images.githubusercontent.com/57048349/104090333-5c1daf80-5276-11eb-8b63-f5f6bafd0e27.png)

2021-01-11 08:25 UTC, pkierat-epam requested changes
Let's have those changes implemented for starters.

2021-01-11 08:25 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +        return new Object[]{ 40, 41, 42, 43, 44, 45};
Again, magic numbers despite we have the `Color` enum.

2021-01-11 08:25 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        void act(int i, int j);
This change simplifies the signature and decouples it from the representation of bricks. I like it! :+1:

2021-01-11 09:12 UTC, pkierat-epam commented
> A question about tests. Jacoco shows that I did not cover the test for Painter class which is utility class, is it a normal behavior of that plugin? can I change that somehow?

What Jacoco shows as not covered is the constructor for the Painter class. This class is meant to be a utility class, but it's not protected against instantiating (which is a recommended thing to do). Due to that, Jacoco thinks this code may be used at some point but it's not covered by the tests, since you actually don't call the constructor anywhere. There is an easy way to fix it: make the constructor explicit and private. That will hint Jacoco, that this is a utility class and it won't include it in the coverage report.

2021-01-11 09:26 UTC, pkierat-epam commented
> I decided to change the game's block sing from '#' to empty string because paint method color a background. Such a block looks a little bit better:

I agree, it does look better in the normal mode.

However, there is a side effect: you no longer can easily analyze the output of the program using text processing tools or tests, since, when you strip the ansi codes, the blocks become indistinguishable from the background. For me, that breaks the existing functionality.

2021-01-11 12:03 UTC, dominikjaniga91 commented on src/main/java/com/epam/prejap/tetris/block/ColorPicker.java
> +        if(block instanceof OBlock) {
I was thinking about that, but I didn't know if I can change the block class, now it's clear, thanks:)

2021-01-11 12:30 UTC, dominikjaniga91 commented on src/main/java/com/epam/prejap/tetris/game/Painter.java
> +    static String paint(String blockSign, int colorId) {
@pkierat-epam  hm that's interesting option but I think I still need to pass the color id to the playfield grid to print block in right color. Otherwise, how can I distinguish one block's mark from another ?

2021-01-11 22:23 UTC, dominikjaniga91 commented
Hi @pkierat-epam 

1. I removed the ColorPicker class by adding a Color field to the Block class. I wanted to pass color id in the Block's constructor but this will break the tests for the concrete Blocks.
2. I restored the block's mark to "#" without background color.
3. I did not move the paint method to Color enum because I'm still passing an ANSI code to the playfield grid. I don't have another idea of distinguishing one block's mark from another in the Printer's print method.

Could you show rebasing with conflicts in the next lecture? I had some problems with rebasing from the master after I pulled Lukasz's changes. Afterward, I couldn't push my changes to origin so I used --force flag.

2021-01-11 22:25 UTC, dominikjaniga91 commented
> > A question about tests. Jacoco shows that I did not cover the test for Painter class which is utility class, is it a normal behavior of that plugin? can I change that somehow?
> 
> What Jacoco shows as not covered is the constructor for the Painter class. This class is meant to be a utility class, but it's not protected against instantiating (which is a recommended thing to do). Due to that, Jacoco thinks this code may be used at some point but it's not covered by the tests, since you actually don't call the constructor anywhere. There is an easy way to fix it: make the constructor explicit and private. That will hint Jacoco, that this is a utility class and it won't include it in the coverage report.

Thank you for the explanation:)

2021-01-12 17:54 UTC, dominikjaniga91 commented
> Could you show rebasing with conflicts in the next lecture? I had some problems with rebasing from the master after I pulled Lukasz's changes. Afterward, I couldn't push my changes to origin so I used --force flag.

Alright, now I know that git rebase is not quite a good option:) -> https://www.atlassian.com/git/tutorials/merging-vs-rebasing

2021-01-12 19:04 UTC, pkierat-epam commented
I wouldn't say it's not good... it's just powerful, and with great power comes great responsibility :wink: Showing that is definitely on my list for tomorrow.

2021-01-13 11:20 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Painter.java
> +    static String paint(String blockSign, int colorId) {
The idea - as I understood it - is to ELIMINATE the need for id altogether. Simply use enum instead.

2021-01-13 11:21 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Painter.java
> +    static String paint(String blockSign, int colorId) {
Even if you use ID for ANSI colour - have that in enum.

2021-01-13 11:21 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        colorId = ColorPicker.pick(block);
:+1:

2021-01-13 11:21 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +        return new Object[]{ 40, 41, 42, 43, 44, 45};
Again, :+1:

2021-01-13 11:22 UTC, TJB4epam commented
Please let us know how things are in threads - reply to earlier comments. Also - please resolve conflicts.

Otherwise today this will be closed.

2021-01-13 14:56 UTC, dominikjaniga91 commented on src/main/java/com/epam/prejap/tetris/block/ColorPicker.java
> +        if(block instanceof OBlock) {
I created Color field in Block class, now every concrete block has different color provided in constructor.

2021-01-13 15:01 UTC, dominikjaniga91 commented on src/main/java/com/epam/prejap/tetris/game/Painter.java
> +    static String paint(String blockSign, int colorId) {
I added additional integer field in enum that represent specific constant. I moved paint method from Painter to Color, now this method is called applyFor()

2021-01-13 15:03 UTC, dominikjaniga91 commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        colorId = ColorPicker.pick(block);
Class ColorPicker disappear since every block has its own color field

2021-01-13 15:06 UTC, dominikjaniga91 commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +        return new Object[]{ 40, 41, 42, 43, 44, 45};
I added Color.values() instead of magic numbers

2021-01-13 15:08 UTC, dominikjaniga91 commented
> I agree, it does look better in the normal mode.
> 
> However, there is a side effect: you no longer can easily analyze the output of the program using text processing tools or tests, since, when you strip the ansi codes, the blocks become indistinguishable from the background. For me, that breaks the existing functionality.

I restored block mark to previous "#"

2021-01-14 07:34 UTC, pkierat-epam commented
Nicely done! Merging.
Points: 23.

2021-01-14 07:34 UTC, merged