30 highest score save in .txt file
EPAM-Online-Courses/tetris pull request #35
Opened 2021-01-09 18:56 UTC by lukaszspyra

PR ready for review. One must be careful next time, when proposing new features...

2021-01-11 11:49 UTC, lukaszspyra commented
Description: 
As we want to store all entries which entered HallOfFame, I used Jackson to simplify mapping to/from Jsons into a file. 
Two classes: DataReader and DataWriter take care of file operations with array of json objects (objects are of class HallOfFameMembers).
HallOfFame class - hold its members, uses writer/reader/printer as dependecies as changes state of list of members.
Printer - now takes input from user, so I was considering re-naming it to UI or Console. Also it decides to print only first 25 of its members.
Test of DataWriter - it depends on Reader test and as it writes and reads the file from file system, I would say it like Integration test.
One thing I was not sure about:
If player beats any score from original list it enters HallOfFame - original file holds 10 records, with lowest score one - actually each player will beat it. Json shall hold more than 25 entries - so it will hold every single player, only displaying 25 - maybe it would be good to change requirement to set max. size of HallOfFame to 25?

2021-01-11 11:54 UTC, lukaszspyra commented
Or another solution instead of limiting size of HallOfFame could be that, original list can be saved with e.g. minimum score of 10, so it will keep all player singatures/points, whose managed to bit that.

@TJB4epam Tomasz, can you take a look at description, as now I have doubts how to implement requirement "And - almost forgot - JSON file can hold more, but game displays only first 25 positions."

2021-01-13 11:40 UTC, TJB4epam requested changes

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +    public static void main(String[] args) throws IOException  {
Please HANDLE instead of THROWING. :P

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/DataReader.java
> +package com.epam.prejap.tetris.data;
If this package has all-public members I won't let it in. :P

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/DataReader.java
> +import com.fasterxml.jackson.databind.ObjectMapper;
Good choice.

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/DataReader.java
> +    public HallOfFameMember[] readFromFile() throws IOException {
I honestly am not sure why we have to throw?

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/DataWriter.java
> + * The DataWriter class is responsible for writing data to file of specified {@link DataWriter#path}.
Same remarks as for DataReader class.

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> + * <p>Implementation note: It contains List with {@link HallOfFameMember} read from file.
Y u do that despite warnings?

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> + * <p>Implementation note: It contains List with {@link HallOfFameMember} read from file.
Just in case you forgot: there's a tag for implNote.

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFameMember.java
> +public final class HallOfFameMember implements Comparable<HallOfFameMember> {
Record please.

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/package-info.java
> +/**
Nice. Unexpected, but nice.

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/package-info.java
> +/**
Please - document here a bit more the ONE class that will be made PUBLIC. All other classes in data package are to be encapsulated and HIDDEN from outside. 

In other words: you lack a gateway to your package.

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Printer.java
> +    public void hallOfFame(List<HallOfFameMember> hallOfFameMembers) {
I'd welcome just calling a `toString` method on an appropriate class and having said `toString` encapsulate the logic of printing.

2021-01-13 11:40 UTC, TJB4epam commented on src/main/resources/files/HallOfFame.txt
> +[{
Why is this a txt file and not a json file?

2021-01-13 11:40 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/data/DataReaderTest.java
> +    private final Path path = Paths.get("src/test/resources/testfiles/ReadFileTest.txt");
Nice! Resources and test resources at that.

2021-01-13 11:40 UTC, TJB4epam commented on src/test/resources/testng.xml
> +                <include name="DataReader"/>
I want a group of groups for IO data.

I want IO tests to be in integration tests, ran by failsafe.

I don't want test groups to be yet another way to call tests encapsulated in a class. 

We suggest a "HallOfFame" group for all related tests, using all involved test, classess, subgroups.

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Printer.java
> +    public HallOfFameMember readInitials(final int score, Scanner in) {
One improvement here: to keep the game fully automatic - have these initials pulled from current user name. This may be dependent on given operating system, so look up necessary API.

2021-01-13 11:40 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Printer.java
> +    public HallOfFameMember readInitials(final int score, Scanner in) {
We suggest `System.getProperty("user.name");`

2021-01-13 11:42 UTC, TJB4epam commented
> Or another solution instead of limiting size of HallOfFame could be that, original list can be saved with e.g. minimum score of 10, so it will keep all player singatures/points, whose managed to bit that.
> 
Regarding:

> @TJB4epam Tomasz, can you take a look at description, as now I have doubts how to implement requirement "And - almost forgot - JSON file can hold more, but game displays only first 25 positions."

and

> If player beats any score from original list it enters HallOfFame - original file holds 10 records, with lowest score one - actually each player will beat it. Json shall hold more than 25 entries - so it will hold every single player, only displaying 25 - maybe it would be good to change requirement to set max. size of HallOfFame to 25?

JSON is limited by OS file length. It can hold thousands of entries. Game should display only a limited amount of those entries - for now. Perhaps that will change in future. Original file holds 10 - that is, every person getting the game gets a file with same 10 inputs.

2021-01-14 11:09 UTC, TJB4epam commented
Further new changes merged. Also, please make sure to reply to previous comments.

2021-01-14 11:15 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +    public static void main(String[] args) throws IOException  {
I  was not sure if IOException shall let the game run, but actually it is just missing the high scores. Changed IOException throwing for try/catch in DataReader and DataWriter classes - detailed explanations on respective classes' comments.

2021-01-14 11:17 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/DataReader.java
> +    public HallOfFameMember[] readFromFile() throws IOException {
Replaced by try/catch printing error message and returning empty array, which will be considered in tryToEnterHallOfFame() which will return false saving user's time of inputting credentials.

2021-01-14 11:17 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/DataWriter.java
> + * The DataWriter class is responsible for writing data to file of specified {@link DataWriter#path}.
Replaced by try/catch printing error saving to file.

2021-01-14 11:27 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/DataReader.java
> +import com.fasterxml.jackson.databind.ObjectMapper;
Thank you, wasn't sure about it but API appeared quite user friendly.

2021-01-14 11:31 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> + * <p>Implementation note: It contains List with {@link HallOfFameMember} read from file.
I was using some jdk class as pattern, which was implemented before Java8 tags were introduced, so probably it caused omission of usage dedicated tag - fixed with implNote, thanks.

2021-01-14 11:32 UTC, lukaszspyra commented on src/test/java/com/epam/prejap/tetris/data/DataReaderTest.java
> +    private final Path path = Paths.get("src/test/resources/testfiles/ReadFileTest.txt");
thank you. It holds file for reading tests, and uses this location to temporary save file for file writing tests.

2021-01-14 11:54 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/HallOfFameMember.java
> +public final class HallOfFameMember implements Comparable<HallOfFameMember> {
Replaced by record, and Jackson still works! :) thanks.

2021-01-14 12:21 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/game/Printer.java
> +    public void hallOfFame(List<HallOfFameMember> hallOfFameMembers) {
I would thinks aobut it, bu it makes perfect sense :) Moved logic to toString() of HallOfFame

2021-01-14 12:30 UTC, lukaszspyra commented on src/main/resources/files/HallOfFame.txt
> +[{
Did not think it can have other extension than .txt, replaced by json.

2021-01-14 13:29 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/game/Printer.java
> +    public HallOfFameMember readInitials(final int score, Scanner in) {
Okay, replaced as suggested to be automatic. String from properties is feed as parameter to readInitials() to allow mock testing

2021-01-14 14:21 UTC, lukaszspyra commented on src/test/resources/testng.xml
> +                <include name="DataReader"/>
Tests rearranged as required (IOData as complete group in integration, remaining groupped under HallOfFame in unit tests

2021-01-14 15:14 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/game/Printer.java
> +    public HallOfFameMember readInitials(final int score, Scanner in) {
Due to automatic data reading, method changes main responsibility to create new member out of data - so it is no longer part of printer, only of HallOfFame - relocated.

2021-01-14 15:15 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/DataReader.java
> +package com.epam.prejap.tetris.data;
Remained only one public class - HallOfFame

2021-01-14 15:23 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/package-info.java
> +/**
Ok, at the moment HalOfFame is the only one public class. The reason remaining classes were public was due to initialization in main of Tetris (Reader/Writer) - now they are initialized in HallOfFame constructor, which looks weird as takes only one parameter (for tests and mocking second constructor is created, allArgs). I did not have any better idea to create kind of gateway.

2021-01-14 15:26 UTC, lukaszspyra commented
All comments addressed, @TJB4epam  please have a look at a free moment.

2021-01-14 16:32 UTC, TJB4epam requested changes
Looks much better. Not far from merging.

2021-01-14 16:32 UTC, TJB4epam commented on pom.xml
> +    <version>0.11</version>
Ah, how quickly this climbs. But I seem to have seen version 1.0 at some PR. Are you sure that's correct?

2021-01-14 16:32 UTC, TJB4epam commented on pom.xml
> +            <version>2.11.3</version>
Version in properties please.

2021-01-14 16:32 UTC, TJB4epam commented on pom.xml
> +            <plugin>
By any chance isn't this added by your IDE the same way it happened during last lecture?

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/DataReader.java
> +            System.err.println("Error occurred when reading from file");
What kind of error? Which file? More specific error details please. Also - how do you plan to resolve the error situation? Right now the messages gives VERY little in that regard.

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/DataWriter.java
> + * The DataWriter class is responsible for writing data to file of specified {@link DataWriter#path}.
See above.

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +
Superfluous. Please cut.

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> + * Represents highest number of points in tetris game.
Does it really represent a NUMBER? (EDIT: also, a SINGLE one?)
Also, Tetris, not tetris. That's a name.

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> +    public HallOfFame(final DataReader reader, final DataWriter writer, final Printer printer, final List<HallOfFameMember> members) {
Why public? How classes outside of a package are to get a DataWriter?

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> +    public HallOfFame(final Printer printer) {
I'd like for this c-tor to call the other one. EDIT: cut an incorrect part.

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFameMember.java
> +    public String toString() {
What was wrong with the one record had?

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFameMember.java
> +record HallOfFameMember(@JsonProperty("name") String name,
Nice, thank you.

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFameMember.java
> + * The HallOfFameMember record represents {@link HallOfFameMember#name} and {@link HallOfFameMember#points} of player with highest scores
My suggestion would be:
```
One line in (link here) HallOfFame of our Tetris game, consisting of name and points earned.
Here I would put line 9 in your current JD, followed by line 11.

@see HallOfFame
```

Tetris. Tetris. Tetris. Tetris. Repeat after me. Tetris. Capital. Letter. For. A. Name. Like. Łukasz. Not. Like. łukasz. :P

2021-01-14 16:32 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Printer.java
> +    public void hallOfFame(HallOfFame hallOfFame) {
:+1:

2021-01-14 16:32 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/data/DataReaderTest.java
> +    public static Object[][] defaultInitialHallOfFame() {
What about IntStream? `IntStream.range(1,11).map(i -> new HallOfFameMember("P"+i, i)).toArray()`? Last part may require a different call (or specifying the array for type safety) but it's one line instead of 11 very repetitive ones. Also, the vars are anonymous and will be collected faster in my approach.

2021-01-14 16:32 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +    public static Object[] mockHallOfFameMembers() {
Yeah, mock all of them! Belittle them, demean them, who the hell they think they are!

;-)

Nice name. :D

2021-01-14 16:32 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +        HallOfFameMember[] mock1 = new HallOfFameMember[]{
Similarly to your other DPs, these here could use some improvements with for loops or IntStreams.

2021-01-14 16:32 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +    @Test(groups = "TryToEnter", dataProvider = "mockHallOfFameMembers")
Grouping and later depending on those groups is quite nice.

2021-01-14 16:32 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +        softAssert.assertAll("Shall add element to list once, but it did not");
Shall add but it did not - Should have added then.

2021-01-14 16:32 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +        softAssert.assertTrue(containsNewMember);
Nice usage of a soft assertion.

2021-01-14 16:32 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +
Why? Superfluous, please cut.

2021-01-14 20:29 UTC, lukaszspyra commented on pom.xml
> +    <version>0.11</version>
Yes, a merge happened meantime. Corrected.

2021-01-14 20:34 UTC, lukaszspyra commented on pom.xml
> +            <plugin>
Yes, when I started to use Records on jdk14 IDE inserted it automatically, maven plugin doesn't compile without it.

2021-01-14 20:38 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> + * Represents highest number of points in tetris game.
Corrected to * Contains members with highest scores in Tetris game.

2021-01-14 20:39 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> +    public HallOfFame(final DataReader reader, final DataWriter writer, final Printer printer, final List<HallOfFameMember> members) {
Good point. For test default would be sufficient. Corrected.

2021-01-14 20:45 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> +    public HallOfFame(final Printer printer) {
This one arg constructor calls method requiring reader to obtain members, so it can not reference other constructor first, unless I missed something?

2021-01-14 20:50 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/HallOfFameMember.java
> +    public String toString() {
Removed. It is actually the same :)

2021-01-14 20:53 UTC, lukaszspyra commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +    @Test(groups = "TryToEnter", dataProvider = "mockHallOfFameMembers")
thank you :)

2021-01-14 20:55 UTC, lukaszspyra commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +        softAssert.assertAll("Shall add element to list once, but it did not");
Corrected, also in a few more places.

2021-01-14 20:55 UTC, lukaszspyra commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +        softAssert.assertTrue(containsNewMember);
thank you.

2021-01-14 20:57 UTC, lukaszspyra commented on src/test/java/com/epam/prejap/tetris/game/PrinterTest.java
> +
Shortened to shallPrintInAppropriateColor().

2021-01-14 20:59 UTC, lukaszspyra commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +    public static Object[] mockHallOfFameMembers() {
Empty souls ;)

2021-01-14 21:03 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/HallOfFameMember.java
> + * The HallOfFameMember record represents {@link HallOfFameMember#name} and {@link HallOfFameMember#points} of player with highest scores
Sorry, run search on classes and replaced by Capital letter.

2021-01-14 21:12 UTC, lukaszspyra commented on src/main/java/com/epam/prejap/tetris/data/DataReader.java
> +            System.err.println("Error occurred when reading from file");
Message corrected to be more detailed ("Returned empty array. Error occurred when reading HallOfFame members from file " + path)

2021-01-14 21:23 UTC, lukaszspyra commented on src/test/java/com/epam/prejap/tetris/data/DataReaderTest.java
> +    public static Object[][] defaultInitialHallOfFame() {
That's huge improvent, I like FP but sometimes do not notice good spots to use it. (used: IntStream.range(1, 11).mapToObj(i -> new HallOfFameMember("P" + i, i)).toArray(HallOfFameMember[]::new)). Thank you very much!

2021-01-14 21:32 UTC, lukaszspyra commented on src/test/java/com/epam/prejap/tetris/data/HallOfFameTest.java
> +        HallOfFameMember[] mock1 = new HallOfFameMember[]{
Replaced by IntStreams.

2021-01-14 21:35 UTC, lukaszspyra commented
@TJB4epam All comments addressed. Ready for next review. 

All fixed except constructor of HallOfFame - pls see comments.

2021-01-15 07:38 UTC, TJB4epam approved these changes
Accepted with a caveat rolled into an issue #48

2021-01-15 07:38 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/data/HallOfFame.java
> +    public HallOfFame(final Printer printer) {
That's bad. But it's deadline today so: #48

2021-01-15 07:54 UTC, TJB4epam commented
@lukaszspyra  so your PR is done and I could've merged it but:

1. We lost the ability to run the game 

Error: LinkageError occurred while loading main class com.epam.prejap.tetris.Tetris
	java.lang.UnsupportedClassVersionError: Preview features are not enabled for com/epam/prejap/tetris/Tetris (class file version 58.65535). Try running with '--enable-preview'

2. Not all tests seem to have executed during build - I don't see the tests using colours for one, that Dominik has introduced.

Without those two being brought back I can't merge ANY PRs.

2021-01-15 10:36 UTC, lukaszspyra commented
I am having a look at it right now.

2021-01-15 12:04 UTC, lukaszspyra commented
Tests are solved, but for --enable-preview there is no such config for jar-plugin...

2021-01-15 14:10 UTC, TJB4epam commented
Almost but no cookie: 

```
Time: 00:00:20
+--------------------+
|         #          |
|         #          |
|         ##         |
|        ##          |
|         #          |
|       # #          |
|       ###          |
|       ##   ###     |
|        ##  ###     |
|       ##    ##     |
+--------------------+
Total score: 7
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
	at com.epam.prejap.tetris.data.DataReader.readFromFile(DataReader.java:30)
	at com.epam.prejap.tetris.data.HallOfFame.obtainMembers(HallOfFame.java:39)
	at com.epam.prejap.tetris.data.HallOfFame.<init>(HallOfFame.java:28)
	at com.epam.prejap.tetris.Tetris.main(Tetris.java:93)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 4 more
```

No fat jar - dependency is NOT present when we launch the JAR file.

2021-01-15 14:44 UTC, lukaszspyra commented
@TJB4epam  Please have a look now. Add maven shade plugin to create fat jar. Playing with pom is like disarming a bomb.

2021-01-15 15:17 UTC, lukaszspyra commented
Still fixing tests after merge...

2021-01-15 15:26 UTC, pkierat-epam commented
![image](https://user-images.githubusercontent.com/70664429/104745503-78c25780-574e-11eb-94c1-718628f09ac5.png)

2021-01-15 15:27 UTC, merged

2021-01-15 15:28 UTC, pkierat-epam commented
Points: 54