4 implement Z block and the common test class for all blocks
EPAM-Online-Courses/tetris pull request #39
Opened 2021-01-11 04:44 UTC by NikaAvramchuk

This Pull Request introduce  Z-shaped block as mentioned on issue #4. In order to avoid code duplications I also decided to implement BlockTest class which using a factory method in BlockTestFactory class can test all blocks derived from the superclass Block. If you approved my idea, I could add all Block`s subclasses to the BlockTestFactory.

I didnt add Z-block tests to BlockFeedTest, because I saw that Lukasz replaced the concept proposed by his predecessors with the factory method, so its better to add  z-block there when Lukasz`s pull request will be approved.

2021-01-11 10:53 UTC, NikaAvramchuk commented
I`m also not sure about the structure in the BlockTestFactory class. Maybe it`s better not to create inner block classes with data providers, but to create a new package with all that classes separately. I guess having too many inner classes is not very good

2021-01-12 12:19 UTC, pkierat-epam requested changes
Good idea with unifying the `*Block` tests, but I'm afraid you won't avoid hard-coding the dots/spaces. Fortunately, it can be delivered in the form of a data provider. The difficulty here is to make the test readable.

Please remove the unnecessary complexity and refactor it to use fixed expected results instead of testing "idem per idem".

2021-01-12 12:19 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +        byte actualValue = childBlock.dotAt(row, col);
One reasonable benefit from those tests is that they check if the `dotAt` method returns a value actually taken from the underlying image, or that the constructor of the child class passes the image correctly to the `Block` class. That, however, may simply be checked using a single instance of each block (no need to create another instance, especially by reflection) and comparing the `dotAt` result directly with the content of the `Block.image` field.

2021-01-12 15:03 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +public class BlockTest {
I see your point. After I pushed last commits, I also thought that my tests did not create a separate system of values, but compared the same system with itself. I supplied such fixed values in the previous version (37bf321 commit), but I didn't like that it made the code very crowded. So I decided to do smth else, but I was wrong :)  So, I'll will return and improve the previous version after work.

2021-01-12 15:13 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +public class BlockTest {
@pkierat-epam Can you please just look at that previous versions and confirm that I understand you correct? Now I have another idea of grouping that data providers, but to avoid misunderstanding, are you talking about creating such system of fixed dots and empty spaces as I did in 12b0818 and 37bf321 commits?

2021-01-12 20:19 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +        byte[][] actualImage = childBlock.image;;
this line of code no longer exists

2021-01-12 20:19 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +        byte actualValue = childBlock.dotAt(row, col);
this line of the code no longer exists

2021-01-12 20:20 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +        byte[][] actualImage = childBlock.image;;
this line of code no longer exists

2021-01-12 20:25 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +public class BlockTest {
@pkierat-epam I pushed new changes, also I`m not sure if you like this concept. I really don`t want this code to be huge and  repetitive, so I try different approaches. I`m afraid that  in the end you will tell me just to code that dots and spaces without creating new classes..

2021-01-12 20:36 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +public class BlockTest {
It's actually kinda weird idea with those dots and spaces in tests (I know it's not yours, don't blame you). Why split them at all? :thinking:

I would make it as simple as possible (but not simpler) and merge those two lists of points into some clean representation of a block. (After all, it's just about checking if the block looks according to the spec, right?)

2021-01-12 20:45 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +public class BlockTest {
What do you mean by "some clean representation of a block"? Image?

2021-01-12 20:47 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +public class BlockTest {
I know that it was not my idea (that dots and spaces), but that tests were approved, and I felt obliged to include them :)

2021-01-13 11:25 UTC, TJB4epam commented
Please take care of conflicts today, otherwise this will be closed despite the potential it has.

2021-01-13 15:25 UTC, NikaAvramchuk commented
> Please take care of conflicts today, otherwise this will be closed despite the potential it has.

2021-01-13 15:29 UTC, NikaAvramchuk commented
@TJB4epam I resolved the conflicts and even closed pull request by mistake :)

2021-01-14 07:14 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/blocks/IBlockTest.java
> +    private static final int rows = 4;
A naming convention for `static final` fields is SCREAMING_SNAKE.

2021-01-14 07:14 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/blocks/IBlockTest.java
> +public class IBlockTest extends BlockForTest {
Classes with names that end with a "-Test" suffix are assumed (by convention) to be tests. The `BlockForTest` name, while clear w.r.t. intention, may therefore be confusing for people and testing frameworks/libraries.

The difference between between `SomethingTest` and `TestSomething` is that the former is a test for something, and the latter is a something used for tests.

2021-01-14 08:01 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +        byte actualValue = childBlock.dotAt(row, col);
Do you want me to introduce such test in the recent version?

2021-01-14 11:10 UTC, TJB4epam commented
Further new changes merged. Also, please make sure to reply to previous comments (if you missed any).

2021-01-14 12:46 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/blocks/IBlockTest.java
> +    private static final int rows = 4;
Done!

2021-01-14 12:49 UTC, NikaAvramchuk commented on src/test/java/com/epam/prejap/tetris/block/blocks/IBlockTest.java
> +public class IBlockTest extends BlockForTest {
This is a very important remark, did not know about this convention. Thank you for it!

2021-01-14 13:09 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +        byte actualValue = childBlock.dotAt(row, col);
Nope, tests based on explicitly passed values are enough.

2021-01-14 13:21 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +public class BlockTest {
There's a class of tests called "acceptance tests". Such tests are often meant to be prepared by people that are not necessarily technical, e.g. business analysts. They like to have a representation which is readable for mere mortals. For example, they might prefer to have something like:
```
"""
#_
#_
##
"""
```
instead of:
```
new Object[][]{
            {0, 0, 1},
            {0, 1, 0},
            {1, 0, 1},
            {1, 1, 0},
            {2, 0, 1},
            {2, 1, 1}
};
```
Contrary to the second form, the first one is more visual, while still being strict and unambiguous.

When you write tests, you want them to be as readable as possible (even more than the prod code), since this is what your testers and new developers in the team will read and learn from.

2021-01-14 13:22 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/tetris/block/BlockTest.java
> +public class BlockTest {
That said, I don't expect from you to implement it now.

2021-01-14 13:34 UTC, pkierat-epam commented
Nice duplication reduction in tests. Merging!
Points: 33

2021-01-14 13:34 UTC, merged