55 add y block
EPAM-Online-Courses/tetris pull request #58
Opened 2021-06-03 19:25 UTC by asilenko

Solved  Issue #55 Add "Y" block.
YBlock Class added with tests and javadoc.

2021-06-07 08:54 UTC, TJB4epam reviewed
Close to finish. Few small remarks, largest thing TBD is testng groups.

2021-06-07 08:54 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/block/YBlock.java
> + * @author Anna Silenko
Please, keep the JD order with the tags.

2021-06-07 08:54 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/block/YBlock.java
> + *
No need for this empty line, please cut, superfluous.

2021-06-07 08:54 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/block/YBlock.java
> +}
All files should have an empty line at the end.

2021-06-07 08:54 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/YBlockTest.java
> +    @DataProvider
Cool. The only thing to improve would be to GROUP the tests.

Please, create a necessary testng.xml file with the config. See TestNG docs for an example file and info on groups.

All tests should belong to some groups.

2021-06-08 15:59 UTC, asilenko commented on src/main/java/com/epam/prejap/tetris/block/YBlock.java
> +}
Empty line added.

2021-06-08 16:00 UTC, asilenko commented on src/main/java/com/epam/prejap/tetris/block/YBlock.java
> + *
Empty line cutted.

2021-06-08 16:00 UTC, asilenko commented on src/test/java/com/epam/prejap/tetris/block/YBlockTest.java
> +    @DataProvider
Tests grouped.

2021-06-08 16:06 UTC, asilenko commented
Ready for review.

2021-06-11 08:29 UTC, TJB4epam approved these changes
Small things, details, and it can go in.

2021-06-11 09:09 UTC, asilenko commented on src/test/java/com/epam/prejap/tetris/block/YBlockTest.java
> +@Test(groups = {"blockShape"})
Fixed

2021-06-11 09:09 UTC, asilenko commented on src/test/resources/testng.xml
> +                <include name="blockShape"/>
Fixed

2021-06-11 09:09 UTC, asilenko commented
Ready for review

2021-06-14 11:34 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/block/YBlock.java
> + * @author Anna Silenko
Done

2021-06-14 11:37 UTC, marcin-ogorzalek-EPAM commented
@asilenko please resolve the merge conflits

2021-06-14 11:39 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/YBlockTest.java
> +@Test(groups = {"blockShape"})
Done

2021-06-14 11:39 UTC, marcin-ogorzalek-EPAM commented on src/test/resources/testng.xml
> +                <include name="blockShape"/>
Done

2021-06-14 11:40 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/YBlockTest.java
> +@Test(groups = {"blockShapes", "blocks"})
Why do we have a second group `"blocks"` now? What is the reasoning behind this? I'm not saying it is wrong but I'm curious.

2021-06-14 11:41 UTC, marcin-ogorzalek-EPAM requested changes
I'm uncertain about `"blocks"` groupe. What's more, there are merge conflicts.

2021-06-14 11:49 UTC, asilenko commented on src/test/java/com/epam/prejap/tetris/block/YBlockTest.java
> +@Test(groups = {"blockShapes", "blocks"})
Tomasz recommended it https://github.com/EPAM-Online-Courses/tetris/pull/58#discussion_r649792266

2021-06-14 11:57 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/YBlockTest.java
> +@Test(groups = {"blockShapes", "blocks"})
Sorry I missed the last part of that comment.

2021-06-14 12:33 UTC, marcin-ogorzalek-EPAM approved these changes
Conflicts solved, doubts explained

2021-06-14 12:37 UTC, marcin-ogorzalek-EPAM commented
Well, actually I have one doubt. @asilenko did you modified `TBlock` and tests for it. Content of the previously merged PR appears as something new here. It seems that there is a problem with history (if I am right).

2021-06-14 12:40 UTC, asilenko commented
> Well, actually I have one doubt. @asilenko did you modified `TBlock` and tests for it. Content of the previously merged PR appears as something new here. It seems that there is a problem with history (if I am right).


I did not modify TBlock tests... I have some problem with history :-)  
TBlock has testing.xml outside Test directory. So now there is testing.xml and 'my' testng.xml in Test directory.

2021-06-14 13:15 UTC, marcin-ogorzalek-EPAM commented
As already mentioned by Andrii `rebase` may be a key here.

2021-06-14 16:13 UTC, asilenko commented
I had some trouble with using `git rebase` for the first time. It should be ok now.

2021-06-15 16:18 UTC, TJB4epam requested changes

2021-06-15 16:18 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/TBlockTest.java
> +@Test(groups = {"blockShapes", "blocks"})
I will let that in, but... how is "blockShapes" group different from "blocks"?

2021-06-15 16:19 UTC, TJB4epam commented
Too quick click! POM not bumped up, that's the reason why you don't have conflicts here. :-)

Please, bump up the version in a POM, after all, we're adding a new feature.

2021-06-15 16:22 UTC, asilenko commented on src/test/java/com/epam/prejap/tetris/block/TBlockTest.java
> +@Test(groups = {"blockShapes", "blocks"})
https://github.com/EPAM-Online-Courses/tetris/pull/58#discussion_r649792266
You recommended it?

2021-06-15 16:23 UTC, asilenko commented
Probably ready :-)

2021-06-16 03:25 UTC, asilenko commented on src/test/java/com/epam/prejap/tetris/block/TBlockTest.java
> +@Test(groups = {"blockShapes", "blocks"})
I made some changes in testng.xml to make intentions behind creating both "blockShapes" and "blocks" more clear.

2021-06-16 07:50 UTC, asilenko commented
@TJB4epam would you please take a look?

2021-06-16 19:38 UTC, asilenko commented
Is this the proper solution, you're looking for @TJB4epam ?

2021-06-17 08:07 UTC, marcin-ogorzalek-EPAM commented
@asilenko there is some change that worries me. 2 classes (other shapes) are deleted. Are we removing some functionalities here?

2021-06-17 08:11 UTC, asilenko commented
> @asilenko there is some change that worries me. 2 classes (other shapes) are deleted. Are we removing some functionalities here?

One Test class with @Factory replaced those test classes, as recommended -> https://github.com/EPAM-Online-Courses/tetris/pull/84#discussion_r652426931
This is my first @Factory usage. Did I misunderstood it's concept of it?

2021-06-17 08:53 UTC, marcin-ogorzalek-EPAM commented
@asilenko sorry for my mistake. I took those as removing functionalities (in this case tests) no replacing those with `@Factory`. This my previous comment is invalid.

2021-06-18 06:48 UTC, TJB4epam approved these changes
Nice! Much obliged!

2021-06-18 06:48 UTC, TJB4epam commented on pom.xml
> +    <version>0.5</version>
TY!

2021-06-18 09:20 UTC, merged