14 send block to bottom immediatly
EPAM-Online-Courses/tetris pull request #62
Opened 2021-06-05 16:12 UTC by rpiw

Implement keyboard handling with JNativeHook library. Allow user to control the block with 'h', 'l' and arrow down buttons. To run as a human player send **human** string as a parameter to jar. Introduce simple logging facility with log4j library for debugging. 

To sum up: solve #14 issue

2021-06-09 06:14 UTC, TJB4epam commented on pom.xml
> +            <version>2.0.2</version>
A good practice that we would like to follow is to keep all version numbers in the properties:

```
<properties>
<version.jnativehook>2.0.2</version.jnativehook>
...
</properties>
```

To use it:

```
<version>${version.jnativehook}</version>
```

Applies to all version numbers, of plug-ins, of dependencies, all.

2021-06-09 06:14 UTC, TJB4epam commented on pom.xml
> +                        <phase>none</phase>
I'm curious - why none?

2021-06-09 06:14 UTC, TJB4epam commented on pom.xml
>                  <version>3.2.0</version>
As above (version number).

2021-06-09 06:14 UTC, TJB4epam commented on pom.xml
> +                            <mainClass>com.epam.prejap.tetris.Tetris</mainClass>
Good fix, thank you!

2021-06-11 07:07 UTC, TJB4epam reviewed
Large change so many comments. I'm worried about insufficient test for the scope of the change.

2021-06-11 07:07 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Move.java
> +    TO_BOTTOM_NOW(NativeKeyEvent.VC_DOWN)
AFAIR that's arrow down key code? If so, move left is on h, move right is on l and move down is on... arrow down? Completely elsewhere?

2021-06-11 07:07 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +    private static final int MOVE_IMMEDIATELY_TO_BOTTOM = NativeKeyEvent.VC_DOWN;
Different name than in other places. Also, why are we having same data local to two different places? If I will want to change keyboard mappings I'm to change them twice or suffer the consequences?

2021-06-11 07:07 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +    public Optional<Move> nextMove() {
Why are we using Optional here?

2021-06-11 07:07 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +        return switch (key) {
New switch syntax - nice.

2021-06-11 07:07 UTC, TJB4epam commented on src/main/resources/log4j2.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Hmmm.... Sooo.... We are using commons logging, the built-in JAVA library... and yet we use log4j config file? How does that work together?

2021-06-11 07:07 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> +    public void TestMoveWithMoveToBottom() {
What about tests about previously working moves? With the scope of this change I'd really want to have more tests.

2021-06-11 07:07 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +        human.killHumanPlayer();
Charming method name. :P

2021-06-11 07:07 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +    @Test(dataProvider = "provideKeysForMovement")
Have you tested that this test belongs to groups it needs to belong? :suuspiciouus staaaare:

2021-06-11 08:07 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +    private static final java.util.logging.Logger loggerNH = getLogger(GlobalScreen.class.getPackage().getName());
You do not bite now. Its JNativeHook who bites! The library has its own built-in logger using java.util.logging and by default it spams 6 lines every time any key is pressed/released/typed. To disable it, I must first grab its logger, then set the level. And logger from log4j is more human readable output, without any magical numbers and jnative's slogans. So this one must stay here if you do not want to see more output from underlying library than from the tetris itself.

2021-06-11 08:08 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> + * @see https://github.com/kwhat/jnativehook
To be able to capture keyboard input regardless of the underlying OS.

2021-06-11 08:10 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/game/Move.java
> +    TO_BOTTOM_NOW(NativeKeyEvent.VC_DOWN)
It was in issue requirements. I saw you have already changed to vim-like mapping

2021-06-11 08:12 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +    private static final int MOVE_IMMEDIATELY_TO_BOTTOM = NativeKeyEvent.VC_DOWN;
Because custom mapping is another feature and I had to somehow survive without implementing it (another issue). I would prefer to read keys-map from another source to HumanPlayer class. But it was lacking when I was coding

2021-06-11 08:56 UTC, Adam-Szczeblewski-EPAM commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +    private static final java.util.logging.Logger loggerNH = getLogger(GlobalScreen.class.getPackage().getName());
my 3 cents:
- redirect JUL->log4J automagically: https://www.logicbig.com/tutorials/misc/java-logging/jul-to-slf4j.html
- then you'll be able to configure logging level for jnativehook in log4j properties, like everything else
- In general (not related to this particular problem): declare your loggers as slf4j interfaces, not log4j (so you can change implementation at will)

2021-06-14 12:12 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +    <version>0.2</version>
Another update required here

2021-06-14 12:13 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +            <version>2.0.2</version>
Seems to be done

2021-06-14 12:14 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +                <version>3.3.0</version>
This should also be defined in `properties` with a proper variable.

2021-06-14 12:15 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +                        <phase>none</phase>
JAR plugin removed

2021-06-14 12:15 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +        <mainClass>com.epam.prejap.tetris.Tetris</mainClass>
Nice change with this extraction

2021-06-14 12:15 UTC, marcin-ogorzalek-EPAM commented on pom.xml
>                  <version>3.2.0</version>
Not valid anymore as JAR plugin removed

2021-06-14 12:21 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +
done

2021-06-14 12:22 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +
done

2021-06-15 11:49 UTC, rpiw commented on pom.xml
> +                <version>3.3.0</version>
Done

2021-06-15 11:50 UTC, rpiw commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +    @Test(dataProvider = "provideKeysForMovement")
Updated

2021-06-15 11:51 UTC, rpiw commented on src/main/resources/log4j2.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Log4j was erased, no logging atm

2021-06-16 07:30 UTC, TJB4epam requested changes
Per review comments, earlier and later.

2021-06-16 07:30 UTC, TJB4epam commented on src/test/resources/testng.xml
> +</suite>
Bad file ending. Also, please update and resolve conflicts.

2021-06-18 08:21 UTC, TJB4epam requested changes
1. TY for the version increase!
2. Rest in the review.

License is serious issue, pay attention to all comments w.r. to it.

2021-06-18 08:21 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +            System.setOut(null);
Please mark that our project is no longer commercial project and that we're also using an appropriate license. Also, do add license in the code, and mark the repo appropriately.

While I admire the craftiness of this solution, the legal team would have your head were it pulled on a commercial project. :P Ofc, if this is a copyLEFT license, that is.

2021-06-18 08:21 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +            System.setOut(null);
Also, just to be sure - create an issue w.r.t. this and document: license, this trick you're doing here, appropriate documentation from JNativeHook and our subsequent license change. Refer the issue in the README file in this repository.

2021-06-18 08:21 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> +    BlockFeed feed;
Fields are package-private because...?

2021-06-18 08:21 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> + * @author: Radosław Piwowarski
Kill the colon.

2021-06-18 08:21 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> +    public Object[][] provideNumberOfMovesAndExceptedResults() {
Expected, not E_XC_epted, right?

2021-06-18 08:21 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> +                        {1, true, Move.RIGHT},
```
IntStream.of(1,2,5,8).forEach(i -> new Object[]{i, true, Move.RIGHT});
IntStream.of(1,2,5,8).forEach(i -> new Object[]{i, true, Move.LEFT});
```

instead of just array creation, make it add an array to a matrix and you have same code in two lines.

2021-06-18 08:21 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> +                        {1, true, Move.RIGHT},
Plus one if for 9s or take 9s out of an IntStream and add them separately using a third int stream.

2021-06-18 08:21 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +                {'j', Move.TO_BOTTOM_NOW}
Sorry about that, because I actually forgot that in Tetris there's a special key to send to the bottom. Number of Tetris clones uses a key to move one line down and a space to move all the way down. Just in case, I'd like to have space here instead of `j` if it's not too much trouble.

2021-06-18 08:21 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +public class TestHumanPlayer {
Having tests is better than not having them. I'm however tempted to asks:

1. where are the unhappy tests?
2. where are the border cases tests?

2021-06-18 08:21 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +
Cut one blank line here please.

2021-06-18 08:21 UTC, TJB4epam commented on src/test/resources/testng.xml
> -<?xml version="1.0" encoding="UTF-8"?>
Not a good idea to cut the info that this is an XML file - why we do this?

2021-06-18 08:21 UTC, TJB4epam commented on src/test/resources/testng.xml
> +    <test name="Playfield">
Naming the entire test scenario "Playfield" doesn't convey any meaning for those who do not understand what PlayField class is. Please, come up with a better scenario name.

2021-06-18 08:21 UTC, TJB4epam commented on src/test/resources/testng.xml
> +    <test name="HumanPlayer">
Why we're separating tests scenarios like that?

2021-06-20 15:03 UTC, rpiw commented on src/test/resources/testng.xml
> +    <test name="HumanPlayer">
Updated

2021-06-20 15:03 UTC, rpiw commented on src/test/resources/testng.xml
> +    <test name="Playfield">
updated

2021-06-20 15:04 UTC, rpiw commented on src/test/resources/testng.xml
> -<?xml version="1.0" encoding="UTF-8"?>
The line was brought back

2021-06-20 15:06 UTC, rpiw commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +
updated

2021-06-20 15:06 UTC, rpiw commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +public class TestHumanPlayer {
Added tests for unexpected keystrokes

2021-06-20 15:08 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +     * @See nextMove()
It does. All tags were corrected. Also, I noticed I was using multi-line comment instead of javadoc. So /* changed into /**

2021-06-20 15:08 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +                {
Corrected

2021-06-22 06:22 UTC, TJB4epam requested changes
I'd like to have answers on some really old remarks. Code-wise - good to go. JDs need more care in few places.

2021-06-22 06:22 UTC, TJB4epam commented on pom.xml
> +                                <descriptorRef>jar-with-dependencies</descriptorRef>
I will never get a reply here, will I?

2021-06-22 06:22 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +         * Not need to distinguish between pressed/released/typed
No need or Not needed.

2021-06-22 06:22 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +         * Not need to distinguish between pressed/released/typed
No need or Not needed.

2021-06-22 06:22 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> +    BlockFeed feed;
Because...?

2021-06-22 06:22 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +                .filter(acceptedKeys::containsKey).map(x -> new Object[]{x}).toArray(Object[][]::new);
Now my comment on rotation keys where I told them "use H and L" is somewhat tricky.

2021-06-22 06:22 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> + * @version 1.0
I don't think we used version anywhere else so why here?

2021-06-22 06:22 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> + * Capture keyboard input with JNativeHook and generate movement based on keystrokes.
Please pay attention to JDs order. Text should not be mixed between see tags but be the first thing to read!

2021-06-22 13:08 UTC, rpiw commented on pom.xml
> +                            <!--                            <finalName>tetris</finalName>-->
final name was removed

2021-06-22 13:17 UTC, rpiw commented on pom.xml
> +                                <descriptorRef>jar-with-dependencies</descriptorRef>
Prefabricated descriptor telling to maven-assembly-plugin to create a JAR which contains the binary output of the project along with unpacked dependencies. Without it, JNativeHook jar should be present in project.

2021-06-22 13:22 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +         * Not need to distinguish between pressed/released/typed
No need

2021-06-22 13:22 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> +         * Not need to distinguish between pressed/released/typed
no need

2021-06-22 13:38 UTC, rpiw commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +                .filter(acceptedKeys::containsKey).map(x -> new Object[]{x}).toArray(Object[][]::new);
I will fix it when keys mapping come in

2021-06-22 13:38 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> + * @version 1.0
removed

2021-06-22 13:38 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/player/HumanPlayer.java
> + * Capture keyboard input with JNativeHook and generate movement based on keystrokes.
fixed

2021-06-22 13:52 UTC, rpiw commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> +    public void TestMoveWithMoveToBottom() {
added more tests

2021-06-22 13:53 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/player/TestHumanPlayer.java
> +                .filter(acceptedKeys::containsKey).map(x -> new Object[]{x}).toArray(Object[][]::new);
You will or they will. :)

2021-06-22 14:02 UTC, TJB4epam requested changes
requesting changes and answers! I'm sobbing here due to silence!

2021-06-22 14:02 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> + * @author Radosław Piwowarski
Do bicia.

2021-06-22 14:02 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/TestPlayfield.java
> +    BlockFeed feed;
Nadal nie wiadomo, co takiego sprawiło, że pola są pakietowe. :P

2021-06-22 14:02 UTC, TJB4epam commented on src/test/resources/testng.xml
> +    <test name="TestPlayfieldAndHumanPlayer">
Spaces are allowed in test names. So let's use'em!

2021-06-22 14:18 UTC, rpiw commented on src/test/resources/testng.xml
> +    <test name="TestPlayfieldAndHumanPlayer">
done

2021-06-22 14:24 UTC, TJB4epam approved these changes

2021-06-22 14:24 UTC, merged