30 implement score saved in txt
EPAM-Online-Courses/tetris pull request #63
Opened 2021-06-05 19:20 UTC by Svetlanazub

Add feature that save highest player's score to .txt file and print 25 max scores before the current player one.

2021-06-06 19:32 UTC, Svetlanazub commented
Update code for writing and reading JSON file

2021-06-07 21:24 UTC, Winetq commented
Hi @Svetlanazub 
In my opinion there are several things to improve when it comes to syntax:
1. List<Record> scoresList; instead of ArrayList<Record> scoresList; - it's better to use more general types 
2. it's also better to use for example System.err.println(e.getMessage()); instead of e.printStackTrace();
3. and you can also use a try-with-resources statement when you create FileReader or Writer and then you will not have to close these character streams manually (I mean the close() method)

2021-06-09 21:20 UTC, Winetq commented
@Svetlanazub, in my opinion very nice jobbb :). We will see what Tomasz is going to say :)

2021-06-10 19:30 UTC, Svetlanazub commented
@Winetq Thank you for feedback.

2021-06-14 14:02 UTC, TJB4epam commented
Hi @Svetlanazub - please update the conflicted files.

2021-06-14 14:12 UTC, TJB4epam requested changes
Several things to change and despite me not commenting on other files, I've found things that should be looked at across all files (Javadocs). Not bad looking, but serious improvement is required!

2021-06-14 14:12 UTC, TJB4epam commented on data/score_list.json
> +[{"name":"BBB","valueOfScore":10000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","val
GitHub warns about this file ending. :(

2021-06-14 14:12 UTC, TJB4epam commented on pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Why we dropped to 11? The project uses 16?

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +
1. It's inelegant to have an empty line between Javadocs and their target. Please cut.
2. We shouldn't start Javadoc from "This javadoc'ced-element", as then first two words of any Javadoc are always "This class", "This interface" or "This method". Instead: "Keeps players...".

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +public class SavedScore {
Why public?

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    public SavedScore() {
Why public?

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    List<Record> scoresList;
Why package?

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    final static int n = 25;
Why package-private?

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +            System.out.println();
:O :O :O For the love of sane settings, what is that? :-1:

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +        } catch (IOException e) {
I have a feeling multicatch might be useful here.

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +     * This method is used to write a new score to the JSON file if it is in the range of 25 max scores.
Same remark as with "This class" earlier on. And please apply in all other places where JD begins with "This something".

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    public void rewriteSavedScore(int currentPoints, String nameNewScore) {
A public API that has a void return type. That calls for serious pause. Why we want to have a public API for SavedScore be a side-effect-using-procedure?

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +        try (Writer writer = Files.newBufferedWriter(Paths.get("data/score_list.json"))){
1. What is data folder? How we make sure our Tetris game has that?
2. Magical string here. 
3. Nice usage of `Files.newBufferedWriter`, kudos!

2021-06-14 14:12 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +      //          case LEFT -> moveLeft();
Usually we want to avoid pushing commented code to the repository. Any reason not to do so here?

2021-06-14 14:12 UTC, TJB4epam commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +
Way too many blank lines between Javadocs and their targets. Please avoid doing that. Some tools may omit such Javadocs entirely.

2021-06-14 14:12 UTC, TJB4epam commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +    @BeforeSuite (groups = {"SavedScoreTest"})
Group names should be plural, as they hold more than one test.

2021-06-14 14:12 UTC, TJB4epam commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +     * This method tests if the line with player's name and score is added to the JSON file
JDs for tests are used only for really special cases. Most of the time, method name should be clear enough w.r.t. what we test within.

2021-06-14 20:14 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +     * This method is used to write a new score to the JSON file if it is in the range of 25 max scores.
Fixed

2021-06-14 20:17 UTC, Svetlanazub commented on pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Fixed

2021-06-14 20:19 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +
Fixed

2021-06-14 20:20 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +      //          case LEFT -> moveLeft();
Fixed

2021-06-14 20:21 UTC, Svetlanazub commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +    @BeforeSuite (groups = {"SavedScoreTest"})
Fixed

2021-06-14 20:21 UTC, Svetlanazub commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +     * This method tests if the line with player's name and score is added to the JSON file
Fixed

2021-06-16 14:42 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +            System.out.println();
I’m sorry for my oversight.

2021-06-16 18:29 UTC, Svetlanazub commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +
Fixed.

2021-06-16 18:43 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +        } catch (IOException e) {
I would like to catch FileNotFoundException separately from other IOExceptions to see the appropriate message. And as  FileNotFoundException is a subclass of IOException it's impossible to multicatch. I see compilation error. It's possible either to have two catches or only IOException. Maybe I'm wrong and there is a better desicion for it?

2021-06-16 19:38 UTC, Svetlanazub commented on data/score_list.json
> +[{"name":"BBB","valueOfScore":10000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","val
fixed

2021-06-16 19:38 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +public class SavedScore {
Fixed

2021-06-16 19:38 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    public SavedScore() {
Fixed

2021-06-16 19:39 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    final static int n = 25;
Fixed

2021-06-16 19:39 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +            System.out.println();
Fixed

2021-06-17 12:51 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +            System.out.println("File doesn't exist!");
Here instead of `System.out.` I would suggest `System.err.` as this is an output stream dedicated for the errors.

2021-06-17 12:52 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Indead

2021-06-17 12:57 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    private final String fileName = "resources/score_list.json";
To be more precise this is no a file name but rather a relative path to it.

2021-06-17 12:58 UTC, marcin-ogorzalek-EPAM commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +        Assert.assertEquals(test.contains("AAA 25000"), true);
Why not the static imports?

2021-06-17 13:10 UTC, marcin-ogorzalek-EPAM commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +public class SavedScoreTest {
In my humble opinion, those tests are the international ones as they are touching the external resources.

Moreover, tell me if I'm wrong but are those tests modify the real scoreboard?  If so this is definitely the wrong thing. Think about making `SavedScore()` a parametrised constructor that takes the path to the `score_list.json` and for tests create a different one in `test/resources` instead of regular `main/resources. This scoreboard for tests should be reset after them.

2021-06-17 13:11 UTC, marcin-ogorzalek-EPAM commented on src/main/tests/com/epam/prejap/tetris/testng.xml
> +</suite>
Please add an empty line at the end of the file.

2021-06-17 13:12 UTC, marcin-ogorzalek-EPAM requested changes
There are changes that have to be made and a question to be ansered.

2021-06-17 19:59 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    public void rewriteSavedScore(int currentPoints, String nameNewScore) {
Fixed

2021-06-17 20:00 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +            System.out.println("File doesn't exist!");
Fixed

2021-06-17 20:00 UTC, Svetlanazub commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    private final String fileName = "resources/score_list.json";
Fixed

2021-06-17 20:01 UTC, Svetlanazub commented on src/main/tests/com/epam/prejap/tetris/testng.xml
> +</suite>
Fixed

2021-06-18 09:22 UTC, TJB4epam commented
Conflicts - please fix.

2021-06-20 19:40 UTC, Svetlanazub commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +        Assert.assertEquals(test.contains("AAA 25000"), true);
Fixed

2021-06-20 19:42 UTC, Svetlanazub commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +public class SavedScoreTest {
Made a parametrised constructor and add other .json file for testing purposes

2021-06-22 06:48 UTC, marcin-ogorzalek-EPAM commented on resources/score_list.json
> +]
Add new line at end of the file.

2021-06-22 06:48 UTC, marcin-ogorzalek-EPAM commented on resources/test_score_list.json
> +[{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","val
Add new line at end of the file.

2021-06-22 06:49 UTC, marcin-ogorzalek-EPAM commented on resources/test_score_list.json
> +[{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","val
BTW why this JSON is formatted so differently than on above?

2021-06-22 06:53 UTC, marcin-ogorzalek-EPAM commented
I have a serious issue here. I tried to run `mvn clean test` but I get something like this
![Screenshot from 2021-06-22 08-51-37](https://user-images.githubusercontent.com/70665397/122877764-3d4c3a80-d337-11eb-8ece-e0b03c873d19.png)

This need to be fixed before the merge.

2021-06-22 06:54 UTC, marcin-ogorzalek-EPAM requested changes
The code does not work while run from command line

2021-06-22 07:27 UTC, Svetlanazub commented on resources/test_score_list.json
> +[{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","val
First one was formatted by ctrl+alt+L shortcut and this wasn't.

2021-06-22 07:32 UTC, Svetlanazub commented on resources/score_list.json
> +]
Fixed

2021-06-22 07:32 UTC, Svetlanazub commented on resources/test_score_list.json
> +[{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"AAA","valueOfScore":25000},{"name":"BBB","valueOfScore":10000},{"name":"BBB","val
Fixed

2021-06-22 18:36 UTC, Svetlanazub commented
Working on fixing this issue.

2021-06-23 20:12 UTC, Svetlanazub commented
Now it works from command line

2021-06-23 20:17 UTC, Svetlanazub commented
@marcin-ogorzalek-EPAM Now it works from command line. Update pom.xml by additing dependency

2021-06-24 17:47 UTC, Svetlanazub commented
@marcin-ogorzalek-EPAM @TJB4epam I fixied my code according to your comments.

2021-06-25 06:34 UTC, rpiw commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +        savedScore = new SavedScore("resources/test_score_list.json");
Small change: extract testes file path as private static final field in a class

2021-06-25 06:37 UTC, rpiw commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +        if (sizeOfPrinting.length > 25) {
No asserts in if else. Prepare exact resource file with expected 25 lines and check if save works as intended. This is important, because people want to run your tests without looking at them. Yes, we are lazy.

2021-06-25 06:57 UTC, rpiw requested changes
So I left the most important changes to code. There may be a more, but deadline is close. The most important (in my opinion) is to separate reading file from constructor and make tests more readable. Mark them as integration tests. To be honest, the better practice doing something with resources is to separate software logic based on resources from managing the resources themself. So 2 classes would be awesome - one class for score list and comparing them and second utility class for reading and writing to file.

2021-06-25 06:57 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
Extract try catch from constructor. Do not read resources in constructor. If you need just to read something, you can use static method

2021-06-25 06:57 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    String nameForNewScore() {
Do we need package-private access? If not, make it private

2021-06-25 06:57 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +        return input.toString();
Entire method is quite complicated, let take a look at 2 in this article: https://www.baeldung.com/java-random-string
But it works, just looks ugly, so low priority

2021-06-25 06:57 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +     * @return String
Remove @return String from toString method. If your toString return something else, you break its contract. So no reason to tell it

2021-06-25 06:57 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/SavedScore.java
> +    private static class Record implements Comparable<Record> {
replace with record feature from java 16:
private record Record(String name, Integer score) implements Comparable<Record> 
It will increase readability if the code

2021-06-25 06:57 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        System.out.println(savedScore.toString());
no need to call toString() inside println, it is called by the method

2021-06-25 06:57 UTC, rpiw commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        SavedScore savedScore = new SavedScore("score_list.json");
extract hardcoded string "score_list.json" to private static final field inside class

2021-06-25 06:57 UTC, rpiw commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +public class SavedScoreTest {
Add @Test(groups = ...) annotations in a class, not need to repeat it in every method

2021-06-25 06:57 UTC, rpiw commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +        savedScore = new SavedScore("resources/test_score_list.json");
extract file path to final field

2021-06-25 06:57 UTC, rpiw commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +        savedScore = null;
dunno what does that null is doing here, is it really necessary? If you want to assign null to savedScore, do it in 21 line where you declared the field

2021-06-25 06:57 UTC, rpiw commented on src/main/tests/com/epam/prejap/tetris/SavedScoreTest.java
> +    void tearDown() throws Exception {
what does the method do? Why to assign null after all tests?

2021-06-25 09:52 UTC, rpiw requested changes

2021-06-25 18:55 UTC, rpiw commented on src/test/java/com/epam/prejap/tetris/SavedScoreTest.java
> +        savedScore = null;
no, no, no, we do not need assign null

2021-06-25 18:56 UTC, rpiw commented on src/test/java/com/epam/prejap/tetris/SavedScoreTest.java
> +        if (sizeOfPrinting.length > 25) {
please, do not use branches inside tests

2021-06-25 18:57 UTC, rpiw commented on src/test/java/com/epam/prejap/tetris/SavedScoreTest.java
> +public class SavedScoreTest {
Annotate this with @Test(groups = {your name group goes here})

2021-06-25 18:59 UTC, rpiw commented on src/test/java/com/epam/prejap/tetris/SavedScoreTest.java
> +    @AfterClass(groups = {"IntegrationSavedScoreTests"})
this is still useless, remove tearDown() completly

2021-06-25 19:22 UTC, pkierat-epam commented on src/test/java/tetris/testng.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Strange location for testng.xml.

2021-06-25 20:23 UTC, pkierat-epam commented
Looks good. Merging.

2021-06-25 20:23 UTC, merged