Game speeding up for every 10 points is implemented
EPAM-Online-Courses/tetris pull request #64
Opened 2021-06-06 12:25 UTC by Hermix-art

Additional logic was added to Waiter class, providing possibility to change game speed after game cycle. When game score achieved is multiple of 10, the delay decreases by 100 ms. (if current delay is higher o equals 100 ms), what causes growing level of game difficulty.

Implementation is based on timeout decrease for .sleep(long timeout) method of current thread.

2021-06-07 21:43 UTC, Winetq commented
Hi @Hermix-art 
As far as I remember static fields should be all in upper case (in the WaiterTest class). Please correct me if I'm wrong :).

2021-06-11 09:11 UTC, TJB4epam requested changes
Love the factories. Hate the lack of groups.

2021-06-11 09:11 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/WaiterTest.java
> +                {1, delay},
If the second param is always "delay" why we put it in the DPs? Why not have a constant and use it in the tests as needed

2021-06-14 14:13 UTC, TJB4epam commented
Has conflicts. Also, look carefully if someone didn't add `testng.xml` file.

2021-06-15 15:44 UTC, TJB4epam commented
See previous comment.

2021-06-15 19:46 UTC, Hermix-art commented on src/main/java/com/epam/prejap/tetris/game/Waiter.java
> -    private final int milliseconds;
I left it as final, but added an additional variable, which represents delay adjustment

2021-06-15 19:46 UTC, Hermix-art commented on src/test/java/com/epam/prejap/tetris/game/WaiterTest.java
> +    @Factory(dataProvider = "dataMethod")
Groups are added now

2021-06-15 19:46 UTC, Hermix-art commented on testing.xml
> +    <test name="delays" >
Groups are added now

2021-06-15 19:47 UTC, Hermix-art commented on src/test/java/com/epam/prejap/tetris/game/WaiterTest.java
> +                {1, delay},
Yep, delay was carried out, so removed it from DPs

2021-06-17 13:33 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +                <version>3.0.0-M5</version>
Why not in `<properie>`?

2021-06-17 13:33 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +                <version>3.0.0-M5</version>
Why not in `<properties>`?

2021-06-17 13:38 UTC, marcin-ogorzalek-EPAM commented
@Hermix-art there are plenty of classes added here. Some even under your nicknames like `@author Grzegorz Konopka` :D  

Check the correctness of the Git history and try to fix it, so this MR will add only your code, not the one already present in the repository.

2021-06-17 21:54 UTC, closed without merging