5 implement i block
EPAM-Online-Courses/tetris pull request #73
Opened 2021-06-07 21:24 UTC by kanybek312

2021-06-08 11:12 UTC, asilenko commented
I'm not sure if there is need to create javadoc for test class.
Other javadoc should probably follow specified order: description, blank line, tags.
This may help:
https://www.oracle.com/pl/technical-resources/articles/java/javadoc-tool.html#format

2021-06-11 08:02 UTC, TJB4epam commented
No description, no review. :P

2021-06-11 10:23 UTC, kanybek312 commented
Thanks, I will check it.

2021-06-11 10:23 UTC, kanybek312 commented
Thanks, I will check it.

2021-06-11 10:25 UTC, kanybek312 commented
> No description, no review. :P

Sorry, I just added it :) . Working on other issues. ;)

2021-06-11 10:26 UTC, kanybek312 commented
> I'm not sure if there is need to create javadoc for test class.
> Other javadoc should probably follow specified order: description, blank line, tags.
> This may help:
> https://www.oracle.com/pl/technical-resources/articles/java/javadoc-tool.html#format

Thanks, I will check it. :)

2021-06-14 13:48 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/block/IBlock.java
> + * It creates I block of tetris
Wrong order of the comments in javadoc. First text of the comment, then `@author`. Last but not least all `@see`.
Also, remember to put an empty line between jd text and `@author`

2021-06-14 13:49 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> + * This class methods of IBlock.
Wrong order in jd

2021-06-14 13:50 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> + * This class methods of IBlock.
Moreover, this comment doesn't make sense in this (test) class. While writing the tests we rather don't to javadocs for them.

2021-06-14 13:55 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +    IBlock b = new IBlock();
You initialise this object before the very first test and then keep reusing it. This puts the risk that tests are not independent. I suggest declaring a filed of type `IBlock` (or even `Block`) and initialising it in proper (non-test) method with `@BeforeMethod` annotation

2021-06-14 13:58 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +    @Test(dataProvider = "IBlock")
This is not a proper use of the data provider. If you are using multiple times the stale object like this "graphical" representation of the block, just create the field as with `IBlock b` at the start. If you are using it only once declare as a variable inside of the test method.

2021-06-14 13:59 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +        Assert.assertEquals(actualResult, expectedResult);
I would suggest using static import to remove `Assert.` from the tests.

2021-06-14 14:00 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +@Test(groups = {"blockShapes"})
This is quite nice. I like the introduction of the tests' group.

2021-06-14 14:02 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +        Assert.assertEquals(actualResult, expectedResult, "We check here I block and row is more than 3");
In the message of an assertion, we putting a comment on what when wrong when the assertion failed. For example, use `String.format` to pass an actual value and de desired one, all with a proper comment.

2021-06-14 14:02 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +        Assert.assertEquals(actualResult, expectedResult, "We check here I block column and it is less than 3");
same as before

2021-06-14 14:04 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/testng.xml
> +</suite>
Please fix `No newline at end of file`

2021-06-14 14:06 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +    public void checkBlockIOfTetris(byte[][] expectedResult){
In general, tests naming here is a little problematic. We should check these things against what? What we should expect here?

Check this article to get familiar with some naming conventions https://dzone.com/articles/7-popular-unit-test-naming

2021-06-14 14:07 UTC, marcin-ogorzalek-EPAM requested changes
There are a few comments to fix. Moreover, you should bump up the project version in the `pom.xml`

2021-06-14 14:08 UTC, marcin-ogorzalek-EPAM commented
@kanybek312 also remember to fix the merge conflict

2021-06-14 20:14 UTC, kanybek312 commented
Fixed merge conflicts

2021-06-14 22:23 UTC, kanybek312 commented
> There are a few comments to fix. Moreover, you should bump up the project version in the `pom.xml`

fixed the comments mentioned and bumped up the project version of 'pom.xml'

2021-06-17 07:54 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/block/IBlock.java
> + * It creates I block of tetris
Done

2021-06-17 07:57 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +    IBlock b = new IBlock();
Ok, you put initialisation inside of the test methods. With that approach, there is no need for a field of type `IBlock`. Local variables are sufficient enought.

2021-06-17 07:58 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +        Assert.assertEquals(actualResult, expectedResult);
done

2021-06-17 08:02 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +        Assert.assertEquals(actualResult, expectedResult, "We check here I block and row is more than 3");
Well, I can see String concatenation now. I liked `String.format` but wished it to be done correctly. Right now an expected value is hardcoded in the messages. What if it would change? What if you forgot to update it?

I have a lecture for you with regard to that topic: https://dzone.com/articles/java-string-format-examples

2021-06-17 08:02 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/testng.xml
> +</suite>
done

2021-06-17 08:02 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/IBlockTest.java
> +        Assert.assertEquals(actualResult, expectedResult, "We check here I block column and it is less than 3");
Done with regard to static imports

2021-06-17 08:06 UTC, marcin-ogorzalek-EPAM submitted a review, later dismissed
There are a couple of remarks not taken into account. There are also new merge conflits.

2021-06-18 05:38 UTC, kanybek312 commented
> There are a couple of remarks not taken into account. There are also new merge conflits.
Remarks are taken into account and merge conflicts are solved.

2021-06-18 20:36 UTC, kanybek312 commented
@marcin-ogorzalek-EPAM resolved the conflicts and added new test class.

2021-06-21 08:06 UTC, TJB4epam approved these changes
Anna's changes made the previous review remaining issues solved / gone. Version is bumped. Merging.

2021-06-21 08:06 UTC, TJB4epam commented on pom.xml
> +    <version>0.6</version>
TY!

2021-06-21 08:07 UTC, merged

2021-06-21 08:50 UTC, kanybek312 commented
> Anna's changes made the previous review remaining issues solved / gone. Version is bumped. Merging.

It very practical experiences! Thanks for each comment!!