002 add j block
EPAM-Online-Courses/tetris pull request #74
Opened 2021-06-08 13:18 UTC by MarekM91

Solved issue #2 Add "J" block and added test for it.

2021-06-11 08:04 UTC, TJB4epam requested changes
No grouping.

2021-06-11 08:04 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/block/JBlock.java
> +
Please cut or move below the closing brace.

2021-06-11 08:04 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/JBlockTest.java
> +@Test
No grouping. :(

2021-06-12 16:12 UTC, MarekM91 commented on src/main/java/com/epam/prejap/tetris/block/JBlock.java
> +
Fixed.

2021-06-12 16:12 UTC, MarekM91 commented on src/test/java/com/epam/prejap/tetris/block/JBlockTest.java
> +@Test
Added group tests.

2021-06-12 16:12 UTC, MarekM91 commented
Fixed and ready for review.

2021-06-16 07:58 UTC, TJB4epam requested changes
Version isn't bumped.
Also - don't you think tests should be common for all blocks? Data provider, factory, and DRY.

2021-06-17 08:46 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/JBlockTest.java
> +@Test
done

2021-06-17 08:46 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/block/JBlock.java
> +
Done

2021-06-17 08:48 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/block/JBlock.java
> + * generated J block
This should be written in proper English. Starting with the upper case latter, end with a dot.

2021-06-17 08:49 UTC, marcin-ogorzalek-EPAM commented
The project's version is not bumped up. Still no DRY in tests.

2021-06-18 06:42 UTC, marcin-ogorzalek-EPAM commented
There is the merge conflict

2021-06-18 06:45 UTC, TJB4epam commented
Reminder about conflicts.

2021-06-18 12:09 UTC, MarekM91 commented
@marcin-ogorzalek-EPAM and @TJB4epam 
Hi, resolved conflicts, and bumped up version.

2021-06-21 06:40 UTC, TJB4epam requested changes
Thank you for bumping the version and resolving conflicts but there are several things to look for and change. Not very large things, to be fair.

2021-06-21 06:40 UTC, TJB4epam commented on pom.xml
> +    <version>0.6</version>
TY!

2021-06-21 06:40 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/BlocksShapesTest.java
> +                {"Tests for YBlock ", actualRowsForYBlock, expectedRowsForYBlock, actualColsForYBlock, expectedColsForYBlock, YBlockDotRepresentation},
Please rework this array of arrays, so that commas are at the beginning of a line instead of at the end. Reason being: now, your change, that introduces new line seems like it deleted an old line and added two lines - just because of a comma. Let's optimize this.

Now: 
line,
line,

I want:
line
,line
,line

2021-06-21 06:40 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/testng.xml
> +<suite name="TetrisSuite" verbose="1" >
Why is this suite introduced here? Why this particular directory? What's the benefit? Will we have a separate tng.xml now for every test group? That's what groups are for?

2021-06-22 05:04 UTC, TJB4epam commented
This Wednesday we will focus on aggresively closing PRs. Just FYI.

2021-06-22 15:08 UTC, MarekM91 commented on src/test/java/com/epam/prejap/tetris/block/BlocksShapesTest.java
> +                {"Tests for YBlock ", actualRowsForYBlock, expectedRowsForYBlock, actualColsForYBlock, expectedColsForYBlock, YBlockDotRepresentation},
Changed

2021-06-22 15:10 UTC, MarekM91 commented on src/test/java/com/epam/prejap/tetris/block/testng.xml
> +<suite name="TetrisSuite" verbose="1" >
Moved to resoruces/testng.xml

2021-06-25 12:29 UTC, marcin-ogorzalek-EPAM commented
There are plenty of conflicts to solve here, especially with regards to the tests and how javadocs are standardised right now.

2021-06-25 15:24 UTC, MarekM91 commented
Resolved conflicts and bumped up version

2021-06-25 18:52 UTC, pkierat-epam requested changes
File to be removed and version to be bumped up (.17?).

2021-06-25 18:52 UTC, pkierat-epam commented on testing.xml
> +<?xml version="1.0" encoding="UTF-8"?>
What's the reason behind this file here if there's src/test/resources/testng.xml?

Another surprise for me is that the name contains 'i' (test**i**ng.xml).

2021-06-25 21:40 UTC, merged