9 remove complete lines implementation
EPAM-Online-Courses/tetris pull request #75
Opened 2021-06-08 21:44 UTC by MintNat

Feature that removes complete line from playfield, all lines that are above are moved down.
Added some javadocs for Playfield class.
Tests are made as inner class, defined inside Playfield class.

2021-06-11 08:18 UTC, TJB4epam requested changes
Please make the changes and I'll review again.

2021-06-11 08:18 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    public static Object[][] gridWithNoFilledLines() throws ReflectiveOperationException {
Grid with empty lines? Or does it matter that line are partially filled? Then:

GridWithPartiallyFilledLines

of

GridWithNotFullyFilledLines

2021-06-11 08:18 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    public static Object[][] gridWithNoFilledLines() throws ReflectiveOperationException {
Also - what is happening if the grid field is NOT present? Does the test count as failed or skipped?

2021-06-11 08:18 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    @Test(dataProvider = "gridWithNoFilledLines")
No grouping. :(

2021-06-11 08:18 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        grid3[0] = Arrays.copyOf(notCompleteLine, cols);
How about

```
IntStream.rangeClosed(1,9).forEach(i -> grid3[i] = Arrays.copyOf(notCompleteLine, cols));
```

And then you can replace 10 lines with grid[x] assignment.

2021-06-11 08:18 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        expectedGrid3[9] = Arrays.copyOf(notCompleteLine, cols);
See earlier comment with IntStream.

2021-06-11 10:53 UTC, MintNat commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    public static Object[][] gridWithNoFilledLines() throws ReflectiveOperationException {
If the field "grid" is not present - test would be failed. I declared it in static block at test class

2021-06-11 17:44 UTC, MintNat commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    public static Object[][] gridWithNoFilledLines() throws ReflectiveOperationException {
> Also - what is happening if the grid field is NOT present? Does the test count as failed or skipped?

If the field "grid" is not present - test would be failed. I declared it in the static block of test class

2021-06-18 07:33 UTC, TJB4epam requested changes
It's better! Few more tweaks ahead. Take a look especially at complexity with array-based solution. Alternative: OOP, objects, like a Grid class.

2021-06-18 07:33 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +        while (numberOfFilledLine >= 0) {
I do get the idea, but the complexity is a tad frightening.

I'd like to iterate the matrix ONCE and get the number of complete lines that way.

Also, since I'll be ITERATING over a matrix, I'd like for the matrix to be ITERABLE. Iterator is a design pattern after all, let's use it instead of hand-rolling our own solution.

Finally, OOP: what if we moved the matrix to it's own class? And had the methods there which allow to move on it? That would significantly decrease the logic in the PlayField class. 
Also, helped with SRP.

2021-06-18 07:33 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/game/Playfield.java
> +     * Removes line with given number.
Articles, removes a line, adds a line, looks for a line. This comment is here, but other JDs here also could use it.

2021-06-18 07:33 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/FailListener.java
> +public class FailListener extends TestListenerAdapter {
TY!

2021-06-18 07:33 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    public static Object[][] GridWithNotFullyFilledLines() throws ReflectiveOperationException {
Java method naming convention! Please adhere to it.

2021-06-18 07:33 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        Field grid = Playfield.class.getDeclaredField("grid");
Let's move this to a separate test case and mark all other tests here as dependent on it, using `dependsOnMethod` parameter in `Test` annotation.

2021-06-18 07:33 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +    @Test(groups = {"functionsTests", "playfieldClassTests"}, dataProvider = "GridWithNotFullyFilledLines")
It seems that all the tests in this class belong to those two groups. Therefore:

1. what is the difference between them?
2. why not have a groups on the entire class?

Additionally, I'd move the DPs to their own class. A LOT of code that way moves to a separate class and allows for this class to only have the tests. See `@Test(dataProviderClass...`.

2021-06-21 07:37 UTC, TJB4epam commented
Conflicts and old remarks.

2021-06-22 05:07 UTC, TJB4epam commented
This Wednesday we will focus on aggresively closing PRs. Just FYI.

2021-06-23 13:25 UTC, pkierat-epam commented
@MintNat, please resolve the conversations which are done.

2021-06-23 15:57 UTC, MintNat commented on src/test/java/com/epam/prejap/tetris/game/PlayfieldTest.java
> +        Field grid = Playfield.class.getDeclaredField("grid");
I've moved my clumsy dataProviders to separate class, but I used dataProviderClass instead of dependsOnMethod.

2021-06-23 16:02 UTC, MintNat commented
> @MintNat, please resolve the conversations which are done.

Sorry, I haven't knew that I should mark it here somehow.
Done!

2021-06-25 09:16 UTC, AndriiVel commented
Approved during the lecture. Please change the version to 0.12

2021-06-25 10:04 UTC, marcin-ogorzalek-EPAM commented
Merge conflict @MintNat

2021-06-25 10:09 UTC, merged