67 add welcome screen on launch
EPAM-Online-Courses/tetris pull request #76
Opened 2021-06-10 08:37 UTC by Winetq

I added a welcome screen as a thread. It is visible for given number of seconds, but there is a possibility to manually close the screen pressing the Esc key. Of course I also provided a test to check this functionality.

To sum up: solve the #67 issue

2021-06-10 11:01 UTC, Adam-Szczeblewski-EPAM commented
JDK has a built-in splashscreen capability, is it worth to roll out a custom solution?
https://docs.oracle.com/javase/tutorial/uiswing/misc/splashscreen.html

Also, your test will fail in most CI environments, as they are headless, and won't allow creating any frames.
Possible solutions:
- provide a CI runner which is not headless
- exclude the test from running in headless environment. in junit [@DisabledIf...](https://junit.org/junit5/docs/5.2.0/api/org/junit/jupiter/api/condition/DisabledIfSystemProperty.html)  could be used. In TestNG - I'm sure there's a similar way

2021-06-13 10:20 UTC, Winetq commented
To be honest I would need more time to implement a splash screen, because I'm struggling with returning null from the getSplashScreen() method. For now I think that my solution is sufficient. BTW I can't remind myself what is the CI runner.

2021-06-13 17:05 UTC, Adam-Szczeblewski-EPAM commented
CI - ContinuoutIntegration. E.g. Github Checks, to executed tests upon git push.

I see there are no Checks in this repo, so no CI is configured at all. So for now - yes, your solution is sufficient.
Might need to exclude this test (as in my bullet point 2) once CI is set up.

2021-06-15 15:43 UTC, TJB4epam commented
Conflict reminder.

2021-06-16 07:56 UTC, TJB4epam requested changes
I LOVE the idea. However, I'd like several changes here.

1. There's no mention about splash screen in this, and I'd like for the docs to say so - that there is such option and that we would like to rework this. Splash screen is pretty much what we're implementing here.
2. Tests for the greeting do not mention that they won't work in a headless env. I'd like for that to be more prominent: group name should reflect it.
3. All-headless-tests group should be done, and greeting tests should NOT be a part of it. 
4. Separate testng.xml file is a nice touch, locating it in test/resources is a nice touch as well, but why did you do it? I can think of a few reasons, people not involved in this PR will be confused. Let's remedy that: rename that file in a meaningful way. Put a comment inside about why it's needed.
5. I can't let it in without bumping the version in the POM.
6. Javadocs should NOT start with "This javadocced-element" because we know that we're reading a class JD or a method one. So reading "This method" on a method is pointless. Kill all "This method" or "This class" or "Name of class class" comment elements - mind you, elements, not entire comments that have them.
7. If you're not gonna use Adam's comments w.r.t. splash screen, add a TODO comment and a new issue. TODO: link to the new issue, in the issue, write that splash screen could be redone and add Adam's comments about it.
8. You are changing the manifest! Sensible... but what about changing the JAR tests that test said manifest? New changes, by @AndriiVel, PR #19.

2021-06-18 06:42 UTC, TJB4epam reviewed
Requesting changes.

2021-06-18 06:42 UTC, TJB4epam commented on pom.xml
> +    <version>0.5</version>
TY!

2021-06-18 06:42 UTC, TJB4epam commented on pom.xml
> +        <version.assertj>3.19.0</version.assertj>
:+1:

2021-06-18 06:42 UTC, TJB4epam commented on pom.xml
> +            <version>3.0.0-M5</version>
Put the version in the properties please.

Also, I have a feeling we already have this?

2021-06-18 06:42 UTC, TJB4epam commented on pom.xml
> +            <version>3.0.0-M5</version>
Checked and indeed we do. Take a look why would it be marked as new in your case. Perhaps git rebase might be in order.

Version still should go to properties, the merged code has it directly on the plug-in too.

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        new Greeting(10000).welcomeThePlayer();
1. Number literals are better written this way: `10_000` - clearer to read.
2. Why this particular magic number? Why not... 10_020?

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Greeting.java
> + * The Greeting class manage the Welcomer thread.
Javadocs should NOT start with "this is the Javadoc for name-of-element element".

This class
This method
This interface
This enum
...
...
...


NO

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Greeting.java
> + * The Greeting class manage the Welcomer thread.
Please change "the Welcomer thread" into a link. Use link, linkplain, or something equivalent.

Alternatively: a `see` tag. 

Also, I'm not sure about a thread being in it's own class, but we shall see when I get there. :-)

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Greeting.java
> +     * The constructor creates the thread.
The constructor... part has to go.

An improvement for you to consider for testability: instead of having a c-tor that creates a thread, perhaps some constructional design pattern? Static factory method? Builder?

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> + * This thread has one task to do which is welcoming the player.
Smart opening choice. I approve!

Good JD, here.

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +        } catch (InterruptedException ignore) {}
Serious bad practice. Please, don't do this. https://www.nurkiewicz.com/2014/05/interruptedexception-and-interrupting.html

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
Are we sure? This kinda feel like malpractice, if I launched the program by mistake, why wouldn't I want to close it?

Then again, the story didn't specify it. So, I leave the end decision in your hands, but in the splash screen user story please note that we should think about it.

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +        setFocusTraversalKeysEnabled(false);
IIRC this disables tab moving focus during the screen's existence. Why we need this for a splash screen?

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +    private void createTheLabels() {
If we return the panel created we can use this code later. Due to splash screen issue - I leave that to you to decide, you can forego this comment.

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +    public void keyTyped(KeyEvent e) {}
If this doesn't deserve a Javadoc comment illuminating others why that's empty...


then this PR doesn't deserve my review! :P

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +     * There is a possibility to manually close the screen pressing the Esc key.
Thanks for the explanation. Please make this a part of program documentation. A sentence like: "you can close the welcome screen with Esc key" will suffice.

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +    public void keyReleased(KeyEvent e) {}
See above. Same thing.

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Greeting.java
> +        this.welcomer = new Thread(new Welcomer(this, milis));
Just FYI: you are allowing for this reference to escape the c-tor PRIOR to c-tor being done. Serious malpractice w.r.t. multithreading. JCIP (Java Concurrency In Practice) is a recommended reading on the matter.

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +            greeting.finishTheWelcoming();
So, if we just rework this, we can have the thread complete normally. A thing worth having!

2021-06-18 06:42 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/greeting/Greeting.java
> +        welcomer.interrupt();
`Thread.currentThread.interrupt` should do from the inside of a thread.

2021-06-18 06:42 UTC, TJB4epam commented on src/test/resources/testng.xml
> +<suite name="Tetris Suite" verbose="1">
Why is "Tetris Test" just a "greeting test"?

Read on suite and test tags from testng.xml file - they carry meanings of set of tests and test scenario, respectively. The names confuse me here.

2021-06-18 06:42 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/greeting/GreetingTest.java
> +@Test(groups = {"greeting"})
All right. Time to get into nitty-gritty details of a multithreaded test realities.

This is no longer a deterministic code. Please have this done with special care.

TestNG has several features for multithreaded tests: thread pool, ability to run the code in a single thread or in multiple threads,  invocation count, multiple invocation of a threaded code methods etc. 

I'd like to see tests that use that here,to verify that multiple threads won't be an issue for the game.

2021-06-18 06:42 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/greeting/GreetingTest.java
> +@Test(groups = {"greeting"})
If you wish to keep the escaped reference (this in Greeting) then do test for whether that's an issue or not.

2021-06-18 06:42 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/greeting/GreetingTest.java
> +                {10000}
Again - numeric literals can use floor as a divider for better readability.

Additionally, I recommend reworking some of that code with `TimeUnit`.

2021-06-18 06:43 UTC, TJB4epam requested changes
Really nice job, and due to thread introduction I had to treat it especially harshly. So - number of changes to introduce, most worrying would be escaping reference and insufficient tests.

Additionally, older remarks are yet to be fully addressed.

2021-06-21 07:15 UTC, TJB4epam commented
Conflicts and older remarks. :(

2021-06-22 05:04 UTC, TJB4epam commented
This Wednesday we will focus on aggresively closing PRs. Just FYI.

2021-06-22 14:26 UTC, Winetq commented on pom.xml
> +            <version>3.0.0-M5</version>
That's true, I don't need this dependency. Other versions moved to properties.

2021-06-22 14:33 UTC, Winetq commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        new Greeting(10000).welcomeThePlayer();
Just because 10_000 :), but it can be changed.

2021-06-22 14:35 UTC, Winetq commented on src/main/java/com/epam/prejap/tetris/greeting/Greeting.java
> + * The Greeting class manage the Welcomer thread.
Javadocs was improved.

2021-06-22 14:41 UTC, Winetq commented on src/main/java/com/epam/prejap/tetris/greeting/Greeting.java
> +     * The constructor creates the thread.
That's a great idea, but maybe next time :).

2021-06-22 15:17 UTC, Winetq commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
It is needed because then the whole application will be killed.

2021-06-22 15:19 UTC, Winetq commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +        setFocusTraversalKeysEnabled(false);
We don't need this :)

2021-06-22 15:33 UTC, Winetq commented on src/main/java/com/epam/prejap/tetris/greeting/Welcomer.java
> +    public void keyTyped(KeyEvent e) {}
Done.

2021-06-22 15:51 UTC, Winetq commented on src/main/java/com/epam/prejap/tetris/greeting/Greeting.java
> +        welcomer.interrupt();
I have problems with the Thread.currentThread.interrupt(), because it works a little differently than the interrupting from another class like in the snippet above.

2021-06-22 17:11 UTC, Winetq commented
I couldn't refer to all remarks because of the lack of time, so we can close this PR.

2021-06-25 12:26 UTC, marcin-ogorzalek-EPAM commented
> I couldn't refer to all remarks because of the lack of time, so we can close this PR.

Closed as requested

2021-06-25 12:26 UTC, closed without merging