4 implement "Z" block
EPAM-Online-Courses/tetris pull request #77
Opened 2021-06-10 14:31 UTC by lniedziela

Solved issue #4 - added "Z" block with tests and javadocs.

2021-06-11 08:39 UTC, TJB4epam requested changes
There's a mixup here with #19 - please take a look and make a call. I'd personally suggest dropping that change since someone else is working on it already.

2021-06-11 08:39 UTC, TJB4epam commented on pom.xml
> +        <main.class>com.epam.prejap.tetris.Tetris</main.class>
Nice - please mark that you're fixing the #19 along the way :-) And... have the tests for it. See I think Andrii's pull request.

Or, you may just drop this or wait till he introduces his changes.

2021-06-11 08:39 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> + * Tests for ZBlock class.
Superfluous. We use Javadoc in tests ONLY when there's a need to document something about those tests. The class names says what we test clearly enough. Please cut.

2021-06-11 08:39 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +@Test(groups = {"blockShapes"})
TY for the plural!

2021-06-11 09:00 UTC, lniedziela commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> + * Tests for ZBlock class.
Javadoc for ZBlockTest deleted.

2021-06-11 09:02 UTC, lniedziela commented on pom.xml
> +        <main.class>com.epam.prejap.tetris.Tetris</main.class>
Thank you for suggestion. Changes dropped.

2021-06-14 14:15 UTC, TJB4epam requested changes
Conflicts ofc, other than that, looks OK.

2021-06-17 13:42 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +                , {1, 2, 1, "Incorrect dotAt(1, 2)!"}
Weird formatting. Please align all braces and put colons at the end.

2021-06-17 13:43 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +        <main.class>com.epam.prejap.tetris.Tetris</main.class>
Indeed

2021-06-17 13:43 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> + * Tests for ZBlock class.
Indeed

2021-06-17 13:43 UTC, marcin-ogorzalek-EPAM commented
@lniedziela there are conflicts for solving before merge

2021-06-17 13:45 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +    @DataProvider
I would sort methods here. Put DP next to each other at the binging or the end of the class not between the tests.

2021-06-17 13:50 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +        assertEquals(actual, expected, "Number of rows for ZBlock is incorrect! Expected: " + expected + ", but actual: " + actual);
Please use `String.format` instead of the concatiantion.

2021-06-17 13:51 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +        assertEquals(actual, expected, "Number of cols for ZBlock is incorrect! Expected: " + expected + ", but actual: " + actual);
Please use `String.format` instead of the concatenation.

2021-06-17 21:53 UTC, lniedziela commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +                , {1, 2, 1, "Incorrect dotAt(1, 2)!"}
It's because of my template. I created it like this, to easily add (or delete) a line, by copying the existing one, without adding a comma at the end.
But I guess you're right, it looks kinda weird. Corrected.

2021-06-17 21:54 UTC, lniedziela commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +    @DataProvider
Done.

2021-06-17 21:54 UTC, lniedziela commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +        assertEquals(actual, expected, "Number of rows for ZBlock is incorrect! Expected: " + expected + ", but actual: " + actual);
Done.

2021-06-17 21:54 UTC, lniedziela commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +        assertEquals(actual, expected, "Number of cols for ZBlock is incorrect! Expected: " + expected + ", but actual: " + actual);
Done.

2021-06-21 06:33 UTC, TJB4epam reviewed
Can't accept. Conflicts and old way of testing new blocks.

2021-06-21 06:33 UTC, TJB4epam commented on src/main/java/com/epam/prejap/tetris/block/BlockFeed.java
> +            TBlock::new,
You have a conflict in this file. Please fix.

2021-06-21 06:33 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +public class ZBlockTest {
See Anna's changes w.r.t. how to test new blocks now. This needs to go / change significantly.

2021-06-21 06:34 UTC, TJB4epam requested changes
Can't accept. Conflicts and old way of testing new blocks.

2021-06-21 21:32 UTC, lniedziela commented on src/main/java/com/epam/prejap/tetris/block/BlockFeed.java
> +            TBlock::new,
Done.

2021-06-21 21:33 UTC, lniedziela commented on src/test/java/com/epam/prejap/tetris/block/ZBlockTest.java
> +public class ZBlockTest {
Done.

2021-06-21 21:54 UTC, lniedziela commented
Conflicts resolved, Anna's changes w.r.t. how to test new blocks included, POM version bumped again, kindly asking for review.

2021-06-22 13:22 UTC, TJB4epam requested changes
Please move this to version .13.

Also - please resolve conflicts.

2021-06-22 13:22 UTC, TJB4epam commented on testng.xml
> +<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
Why is this a new file and why aren't those tests a part of the entire suite and the usual testng.xml file?

2021-06-25 06:19 UTC, lniedziela commented
Bumped POM version to .13.
Also conflicts w.r.t. Nikita changes resolved.

2021-06-25 06:21 UTC, lniedziela commented on testng.xml
> +<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
Deleted unnecessary duplicate testng.xml.

2021-06-25 12:26 UTC, marcin-ogorzalek-EPAM commented
Please resolve conflicts and bump up the version (at least .16)

2021-06-25 17:56 UTC, lniedziela commented
Bumped up POM version to .15. Conflicts resolved.

2021-06-25 18:54 UTC, pkierat-epam approved these changes

2021-06-25 19:28 UTC, merged