create L block with tests
EPAM-Online-Courses/tetris pull request #80
Opened 2021-06-11 13:40 UTC by DzmitryTatarski

2021-06-14 14:09 UTC, marcin-ogorzalek-EPAM commented
Already there are some merge conflicts to solve.

2021-06-14 14:10 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +        </dependency>
Correct me if I'm wrong but this one is a duplicate. Moreover testing library definitely should stay in the `test` scope.

2021-06-14 14:12 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +            <version>7.4.0</version>
I would like to see versions of the dependencies and plugins as in the `properties`. Use the variables to define those and use them in proper places.

2021-06-14 14:13 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/block/LBlockTest.java
> + */
Well we rather avoid creating javadocs in the test classes

2021-06-14 14:14 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/block/LBlockTest.java
> +                String.format("Number of rows is incorrect. Expected: " + expected + "actual:" + actual));
This is how it should be done with plain String not while we are using `String.format`. Please check out how to use variables with regard to that API.

2021-06-14 14:15 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/tetris/block/LBlockTest.java
> +@Test(groups = { "blockShapes" })
I like tests group here

2021-06-14 14:18 UTC, marcin-ogorzalek-EPAM requested changes
There are things to fix. Also resolve the merge conflicts and bump up the project version in `pom.xml`

2021-06-18 06:00 UTC, TJB4epam commented
Conflicts reminder, please resolve.

2021-06-21 07:37 UTC, TJB4epam commented
Conflicts and old remarks.

2021-06-22 05:04 UTC, TJB4epam commented
This Wednesday we will focus on aggresively closing PRs. Just FYI.

2021-06-22 09:18 UTC, closed without merging