42 add H block with tests
EPAM-Online-Courses/tetris pull request #84
Opened 2021-06-15 14:52 UTC by Slawek-Sandbox

Implemented H block (including tests)

2021-06-16 07:35 UTC, TJB4epam requested changes
1. Please update the sources and resolve conflicts.
2. Where's the POM version bump?
3. See review remarks.

2021-06-16 07:35 UTC, TJB4epam commented on src/test/java/com/epam/prejap/tetris/block/HBlockTest.java
> +@Test(groups = {"blockShapes"})
I'm a bit sick of those tests. Why don't we have a proper solution for once, with data providers, factories and one that ELIMINATES all the WhateverBlockTest classes and makes a parametrized test for them all?

2021-06-18 05:59 UTC, TJB4epam commented
Conflicts reminder, please resolve.

2021-06-19 10:58 UTC, Slawek-Sandbox commented on src/test/java/com/epam/prejap/tetris/block/HBlockTest.java
> +@Test(groups = {"blockShapes"})
I see @asilenko have already fixed that. I'm sorry - didn't have time to do it myself quicker.

2021-06-19 16:12 UTC, Slawek-Sandbox commented
I addressed all remarks
Ad 1 Conflicts resolved
Ad 2 POM version bump in
Ad 3 Didn't implement TestNG factory - I see Anna did, but I have refactored BlocksShapesTest class. I hope it counts ;)

2021-06-21 07:45 UTC, TJB4epam requested changes
TY for the version.

Block, instead of String name and actual rows/cols is good for readability.
String.format - excellent choice!

Please, move the factory/dp combo that powers this class up - these are like a c-tor, so should be right after fields.

Actual tests should happen lower.

Overall - a good improvement on Anna's solution, that focuses on readability. I'd like to merge it fast.

2021-06-21 08:07 UTC, Slawek-Sandbox commented
TY for the review.

I moved factory/dp combo up, so test are at the bottom right now. I hope that's what you requested (I was not sure about private helper methods).

2021-06-21 09:56 UTC, Slawek-Sandbox commented
Summary:
- moved factory/dp combo up
- resolved conflicts (which appeared after [5-i-implement-i-block](https://github.com/EPAM-Online-Courses/tetris/pull/73) was merged)
- bumped POM version again

PR should be ready to merge.

2021-06-21 12:28 UTC, TJB4epam approved these changes
Thanks!

2021-06-21 12:28 UTC, merged