79 add logger
EPAM-Online-Courses/tetris pull request #91
Opened 2021-06-18 01:48 UTC by AndriiVel

This PR fixes issue #79 where logging was requested.

**Changes according to request:**
Tinylog is used as a logging library.
Config file for logging is present under the following path: src/main/resources/tinylog.properties

**Default settings:**

* Logs to a file under path: "logs/". Example name of a log: "2021-06-18_0.log" where 0 is the counter that is increased every time a file exceeds the size limit (see below) or a new game is started on the same date.
* Log files are limited in size to 5MB.
* Logs messages with levels FATAL and ERROR (tinylog levels are ERROR and WARN respectively). More detailed levels are: DEBUG and TRACE. This can be configured in src/main/resources/tinylog.properties

The app logs it's **flow** and how pieces (were) **moved** along with final **score**.
The **time** is not logged as it is not yet present in the master branch.
The **tempo** (time passed between printing the screens) is logged.

2021-06-18 08:25 UTC, AndriiVel commented
A small bug/feature question. Every time I start the app, a new log appears

2021-06-21 07:02 UTC, TJB4epam requested changes
I liked how clearly this is done, really. Since we have some doubts about the lib, let's proceed carefully: let's accept it, but provisionally. That means using Anti-Corruption Layer, a DDD tactical pattern. Read on in review remarks.

Also, please use this PR description as a header for a new documentation file, logging, that you should link from readme. Store all the relevant documentation there. 

One more thing: I saw plenty of traces, but very few errors / warnings. Do we really have so little exceptions thrown in our code?

2021-06-21 11:51 UTC, Adam-Szczeblewski-EPAM commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        Logger.trace("New {} is created", getClass().getSimpleName());
doesn't SLF4j exist exactly for that reason? and there is a slf4j-tinylog binding.  (unless you want the LoggingACL as a learning exercise for indirection and implementation hiding, then ignore me)

2021-06-21 12:24 UTC, TJB4epam commented
I don't want to ignore you.... but that is what I wanted 🙂


Tomasz 'TJB' Borek

Lead Training and Development Specialist

https://epa.ms/badgesICollect | Give me a badge<https://heroes.epam.com/>



Email: ***@***.******@***.***>

Kraków, Poland (GMT+1)   epam.com<http://www.epam.com/>



Continuously learning - proud of GeeCON, Polish JUG, SCKRK and Lambda Lounge Kraków!



CONFIDENTIALITY CAUTION AND DISCLAIMER
This message is intended only for the use of the individual(s) or entity(ies) to which it is addressed and contains information that is legally privileged and confidential. If you are not the intended recipient, or the person responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. All unintended recipients are obliged to delete this message and destroy any printed copies.

________________________________
Od: Adam-Szczeblewski-EPAM ***@***.***>
Wysłane: poniedziałek, 21 czerwca 2021 13:51
Do: EPAM-Online-Courses/tetris ***@***.***>
DW: Tomasz Borek (Contractor) ***@***.***>; Comment ***@***.***>
Temat: Re: [EPAM-Online-Courses/tetris] 79 add logger (#91)


@Adam-Szczeblewski-EPAM commented on this pull request.

________________________________

In src/main/java/com/epam/prejap/tetris/Tetris.java<https://urldefense.com/v3/__https://github.com/EPAM-Online-Courses/tetris/pull/91*discussion_r655308948__;Iw!!GF_29dbcQIUBPA!kb-qCg2tSS2Ix6qldfy0NORn1AFCTQf1uoGosWzrJRkdUGDuTyLR_6EYZQxtIC7w0A$>:

> @@ -18,25 +19,35 @@ public Tetris(Playfield playfield, Waiter waiter, Player player) {
         this.playfield = playfield;
         this.waiter = waiter;
         this.player = player;
+        Logger.trace("New {} is created", getClass().getSimpleName());


doesn't SLF4j exist exactly for that reason? and there is a slf4j-tinylog binding. (unless you want the LoggingACL as a learning exercise for indirection and implementation hiding, then ignore me)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/EPAM-Online-Courses/tetris/pull/91*discussion_r655308948__;Iw!!GF_29dbcQIUBPA!kb-qCg2tSS2Ix6qldfy0NORn1AFCTQf1uoGosWzrJRkdUGDuTyLR_6EYZQxtIC7w0A$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AQ3ZMBJI75AAZM7MH6CKX3DTT4RVJANCNFSM464XYSQA__;!!GF_29dbcQIUBPA!kb-qCg2tSS2Ix6qldfy0NORn1AFCTQf1uoGosWzrJRkdUGDuTyLR_6EYZQxGDHcPng$>.

2021-06-21 14:10 UTC, AndriiVel commented on src/main/java/com/epam/prejap/tetris/Tetris.java
> +        Logger.trace("New {} is created", getClass().getSimpleName());
Thank you for your review and comments here!

I was thinking about adding the SLF4J after I read why it became so popular. Although I thought that "one more dependency" is not a good solution, it seems to me now that making changes all over the code (in case we need to switch to a new logging library) is an even worse one :D.

Implementing a custom LoggingACL class sounds challenging, thanks!

2021-06-22 05:09 UTC, TJB4epam commented
This Wednesday we will focus on aggresively closing PRs. Just FYI.

2021-06-22 05:45 UTC, TJB4epam commented
As per announcement: this Wednesday we will aggresively close PRs.

2021-06-22 05:46 UTC, cat-inGlasses commented
@TJB4epam What does it mean "aggresively"?

2021-06-22 05:47 UTC, LIttleAncientForestKami commented
See Teams announcement.

2021-06-23 01:53 UTC, AndriiVel commented on pom.xml
> +        <tinylog.api.version>2.3.2</tinylog.api.version>
Done.

2021-06-23 01:53 UTC, AndriiVel commented on pom.xml
> +                <artifactId>maven-assembly-plugin</artifactId>
This was my change but now it is already in `master` branch.

2021-06-23 01:55 UTC, AndriiVel commented
A note on "Do we really have so little exceptions thrown in our code" - after new PRs were merged, I flavored the code with some more `Logger.error()` :)

Tests are not yet done. I would appreciate information (and examples) on how to mock static methods.

2021-06-23 10:24 UTC, Adam-Szczeblewski-EPAM commented
> Tests are not yet done. I would appreciate information (and examples) on how to mock static methods.

So, you created a problem (static tetris.logger.Logger.error() method), and are now looking for solutions...
Wouldn't it be smarter to avoid creating the problem in the first place? :>

You can just make that method non-static and test it with usual mocking approach. Classes can declare&instantiate a logger instance (as in majority of logging frameworks) and call its non-static methods

Or, if you want to test collaboration of tetris.logger.Logger with tinylog's Logger:
- don't try to mock tinylog's static methods; instead assert on side effects - e.g. check if tetris.logger.Logger.error() produces something into System.err, can use https://github.com/stefanbirkner/system-lambda for it
- if you insist on mocking static methods: https://www.baeldung.com/intro-to-powermock

2021-06-23 11:01 UTC, AndriiVel commented
> Wouldn't it be smarter to avoid creating the problem in the first place? :>
...
> Classes can declare&instantiate a logger instance (as in majority of logging frameworks)

Oh. Indeed. 😅
Thank you for your suggestions!

2021-06-25 06:04 UTC, AndriiVel commented
Unfortunately I didn't finish the tests for logger in time.
I had two approaches which didn't lead to required results.

**1)**
Creating a custom logger class with non-static methods and calling Tinylogs static methods like:
```
package com.epam.prejap.tetris.logger;
public class Logger {
    private static String className;

    private Logger() {
    }

    public static Logger getLogger(String name) {
        className = name;
        return new Logger();
    }
...
    public void error(final Object message) {
        org.tinylog.Logger.error(message);
    }
...
}
```
I tried to test it with suggested "system-lambda" library, however I couldn't capture the required output. Sample test code:
```
package com.epam.prejap.tetris.logger;

import org.testng.annotations.Test;
import org.tinylog.configuration.Configuration;

import static org.testng.Assert.*;
import static com.github.stefanbirkner.systemlambda.SystemLambda.*;

@Test
public class LoggerTestIT {
    private static final Logger LOGGER = Logger.getLogger("Let's roll!"); // instantiating the logger with sample class name

    public void loggerShouldWriteToSystemOut() throws Exception {
        String msg = "Hello!";
        Configuration.set("writer", "console"); // overwriting the output specified in tinylog.properties

        String text = tapSystemOutNormalized(() -> LOGGER.error(msg)); // running the 

        assertFalse(text.isEmpty(), "Logger didn't produce any message to System.out"); // the variable text was empty
    }
}
```
The abovementioned test failed, although I saw the output in the console.

**2)**
I tried instantiating Tinylog in my custom Logger class:
```
package com.epam.prejap.tetris.logger;

import org.tinylog.Level;
import org.tinylog.configuration.Configuration;
import org.tinylog.format.AdvancedMessageFormatter;
import org.tinylog.format.MessageFormatter;
import org.tinylog.provider.LoggingProvider;
import org.tinylog.provider.ProviderRegistry;

public class Logger {
    private static final LoggingProvider LOGGER_IMPL = ProviderRegistry.getLoggingProvider();
    private static final MessageFormatter formatter = new AdvancedMessageFormatter(
            Configuration.getLocale(),
            Configuration.isEscapingEnabled()
    );
    private static String className;

    private Logger() {
    }

    public static Logger getLogger(String name) {
        className = name;
        return new Logger();
    }

    public void error(final Object message) {
        LOGGER_IMPL.log(className, null, Level.ERROR, null, formatter, message);
    }
...
}
```
However with this approach, I had two errors:
1. `LOGGER ERROR: Failed creating service implementation 'org.tinylog.writers.FileWriter'` which I couldn't find how to solve yet.
2. If we modify the tinylog.properties to 
```
writer          =   console
writer.level    =   trace
writer.charset  =   UTF-8
writer.format   =   class : {class}{date: HH:mm:ss.SSS} {level}: {message}
```
adding the `{class}` lead to such error printed into console:
```
LOGGER ERROR: Logger class "com.epam.prejap.tetris.Tetris" is missing in stack trace
class : <unknown class> 07:59:30.582 INFO: Starting the game with 10 rows, 20 columns, and a delay of 500ms
...
```

2021-06-25 09:17 UTC, AndriiVel commented
Approved during the lecture. Version: 0.14
A follow-up issue will be created later (logging the class that called the logger method, writing tests)

2021-06-25 10:57 UTC, marcin-ogorzalek-EPAM commented
Blocked by #82 #109  and merge conflicts

2021-06-25 14:53 UTC, AndriiVel commented
Resolved

2021-06-25 15:24 UTC, TJB4epam approved these changes
A follow-up issue would be for log formats / convention as we lack it ATM, another for log contents identifying components which are responsible for messages, another for lack of tests (garh!) and finally one more for the issues found thanks to logging (why we create two players if one is enough). Nevertheless logging is very important so letting this in.

2021-06-25 15:24 UTC, merged