94 add license
EPAM-Online-Courses/tetris pull request #96
Opened 2021-06-18 12:02 UTC by rpiw

Add GNU GLP license. Update README. #94

2021-06-21 07:17 UTC, TJB4epam requested changes
I don't see WHY we have added this license though? Wasn't it agreed to mention this and allow us to retrofit that decision later if we want to?

2021-06-21 07:31 UTC, rpiw commented
Added explanation in PR. Mention in readme that decision may be retrofitted in any time.

2021-06-22 06:11 UTC, TJB4epam commented on README.md
> +License may be changed in a future if all dependencies distributed under GNU LGP license were removed.
Please add: Current GNU-licensed dependency is JNativeHook.

Also - bump the POM again. Then this can go in.

2021-06-22 06:11 UTC, TJB4epam requested changes
Almost there!

2021-06-22 14:06 UTC, merged